//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod material_request_bulk;
pub mod material_request_item_bulk;
pub mod purchase_order_bulk;
pub mod purchase_order_item_bulk;
pub mod request_for_quotation_bulk;
pub mod rfq_item_bulk;
pub mod rfq_supplier_bulk;
pub mod supplier_quotation_bulk;
pub mod supplier_quotation_item_bulk;

pub use material_request_bulk::MaterialRequestBulkService;
pub use material_request_item_bulk::MaterialRequestItemBulkService;
pub use purchase_order_bulk::PurchaseOrderBulkService;
pub use purchase_order_item_bulk::PurchaseOrderItemBulkService;
pub use request_for_quotation_bulk::RequestForQuotationBulkService;
pub use rfq_item_bulk::RfqItemBulkService;
pub use rfq_supplier_bulk::RfqSupplierBulkService;
pub use supplier_quotation_bulk::SupplierQuotationBulkService;
pub use supplier_quotation_item_bulk::SupplierQuotationItemBulkService;

// <<< CUSTOM
// END CUSTOM
