//! Bulk operations for RequestForQuotation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateRequestForQuotationDto;
use crate::application::service::RequestForQuotationService;
use crate::domain::entity::RequestForQuotation;

/// Bulk operation handler for RequestForQuotation entities.
///
/// Wraps `RequestForQuotationService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type RequestForQuotationBulkService = GenericBulkService<RequestForQuotation, CreateRequestForQuotationDto, RequestForQuotationService>;

// <<< CUSTOM
// END CUSTOM
