//! Bulk operations for RfqSupplier entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateRfqSupplierDto;
use crate::application::service::RfqSupplierService;
use crate::domain::entity::RfqSupplier;

/// Bulk operation handler for RfqSupplier entities.
///
/// Wraps `RfqSupplierService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type RfqSupplierBulkService = GenericBulkService<RfqSupplier, CreateRfqSupplierDto, RfqSupplierService>;

// <<< CUSTOM
// END CUSTOM
