//! Bulk operations for SupplierQuotation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSupplierQuotationDto;
use crate::application::service::SupplierQuotationService;
use crate::domain::entity::SupplierQuotation;

/// Bulk operation handler for SupplierQuotation entities.
///
/// Wraps `SupplierQuotationService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SupplierQuotationBulkService = GenericBulkService<SupplierQuotation, CreateSupplierQuotationDto, SupplierQuotationService>;

// <<< CUSTOM
// END CUSTOM
