//! Bulk operations for SupplierQuotationItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSupplierQuotationItemDto;
use crate::application::service::SupplierQuotationItemService;
use crate::domain::entity::SupplierQuotationItem;

/// Bulk operation handler for SupplierQuotationItem entities.
///
/// Wraps `SupplierQuotationItemService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SupplierQuotationItemBulkService = GenericBulkService<SupplierQuotationItem, CreateSupplierQuotationItemDto, SupplierQuotationItemService>;

// <<< CUSTOM
// END CUSTOM
