//! MaterialRequest DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MaterialRequest;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::MaterialRequestType;
use crate::domain::entity::PurchaseDocStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MaterialRequest
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMaterialRequestDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "request_number")]
    pub request_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(alias = "request_type")]
    pub request_type: MaterialRequestType,
    pub status: PurchaseDocStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "request_date")]
    pub request_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "schedule_date")]
    pub schedule_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MaterialRequest
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMaterialRequestDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "request_number")]
    pub request_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(alias = "request_type")]
    pub request_type: MaterialRequestType,
    pub status: PurchaseDocStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "request_date")]
    pub request_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "schedule_date")]
    pub schedule_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MaterialRequest
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMaterialRequestDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "request_number")]
    pub request_number: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "request_type")]
    pub request_type: Option<MaterialRequestType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PurchaseDocStatus>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "request_date")]
    pub request_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "schedule_date")]
    pub schedule_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl PatchMaterialRequestDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.request_number.is_some() || self.company_id.is_some() || self.request_type.is_some() || self.status.is_some() || self.request_date.is_some() || self.schedule_date.is_some() || self.notes.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MaterialRequest entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MaterialRequestResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub request_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub request_type: MaterialRequestType,
    pub status: PurchaseDocStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub request_date: NaiveDate,
    pub schedule_date: Option<NaiveDate>,
    pub notes: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MaterialRequest entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MaterialRequestListResponseDto {
    /// List of items
    pub items: Vec<MaterialRequestResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MaterialRequestListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MaterialRequestResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MaterialRequestSummaryDto {
    pub id: Uuid,
    pub request_number: String,
    pub company_id: Uuid,
    pub request_type: MaterialRequestType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MaterialRequest> for MaterialRequestResponseDto {
    fn from(entity: MaterialRequest) -> Self {
        Self {
            id: entity.id,
            request_number: entity.request_number,
            company_id: entity.company_id,
            request_type: entity.request_type,
            status: entity.status,
            request_date: entity.request_date,
            schedule_date: entity.schedule_date,
            notes: entity.notes,
            metadata: entity.metadata,
        }
    }
}

impl From<MaterialRequest> for MaterialRequestSummaryDto {
    fn from(entity: MaterialRequest) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            request_number: entity.request_number,
            company_id: entity.company_id,
            request_type: entity.request_type,
            created_at,
        }
    }
}

impl From<CreateMaterialRequestDto> for MaterialRequest {
    fn from(dto: CreateMaterialRequestDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            request_number: dto.request_number,
            company_id: dto.company_id,
            request_type: dto.request_type,
            status: dto.status,
            request_date: dto.request_date,
            schedule_date: dto.schedule_date,
            notes: dto.notes,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MaterialRequest> for MaterialRequestResponseDto {
    fn from(entity: &MaterialRequest) -> Self {
        Self {
            id: entity.id.clone(),
            request_number: entity.request_number.clone(),
            company_id: entity.company_id.clone(),
            request_type: entity.request_type.clone(),
            status: entity.status.clone(),
            request_date: entity.request_date.clone(),
            schedule_date: entity.schedule_date.clone(),
            notes: entity.notes.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMaterialRequestDto> for MaterialRequest {
    fn from_create_dto(dto: CreateMaterialRequestDto) -> backbone_core::ServiceResult<Self> {
        Ok(MaterialRequest::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMaterialRequestDto> for MaterialRequest {
    fn apply_update(mut self, dto: UpdateMaterialRequestDto) -> backbone_core::ServiceResult<Self> {
        self.request_number = dto.request_number;
        self.company_id = dto.company_id;
        self.request_type = dto.request_type;
        self.status = dto.status;
        self.request_date = dto.request_date;
        self.schedule_date = dto.schedule_date;
        self.notes = dto.notes;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MaterialRequest here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
