//! RequestForQuotation DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::RequestForQuotation;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PurchaseDocStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new RequestForQuotation
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateRequestForQuotationDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "rfq_number")]
    pub rfq_number: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "material_request_id")]
    pub material_request_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    pub status: PurchaseDocStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "rfq_date")]
    pub rfq_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "response_due")]
    pub response_due: Option<NaiveDate>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a RequestForQuotation
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateRequestForQuotationDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "rfq_number")]
    pub rfq_number: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "material_request_id")]
    pub material_request_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    pub status: PurchaseDocStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "rfq_date")]
    pub rfq_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "response_due")]
    pub response_due: Option<NaiveDate>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a RequestForQuotation
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchRequestForQuotationDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "rfq_number")]
    pub rfq_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "material_request_id")]
    pub material_request_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PurchaseDocStatus>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "rfq_date")]
    pub rfq_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "response_due")]
    pub response_due: Option<NaiveDate>,
}

impl PatchRequestForQuotationDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.rfq_number.is_some() || self.material_request_id.is_some() || self.company_id.is_some() || self.status.is_some() || self.rfq_date.is_some() || self.response_due.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for RequestForQuotation entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RequestForQuotationResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub rfq_number: String,
    pub material_request_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub status: PurchaseDocStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub rfq_date: NaiveDate,
    pub response_due: Option<NaiveDate>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for RequestForQuotation entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RequestForQuotationListResponseDto {
    /// List of items
    pub items: Vec<RequestForQuotationResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl RequestForQuotationListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<RequestForQuotationResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RequestForQuotationSummaryDto {
    pub id: Uuid,
    pub rfq_number: String,
    pub material_request_id: Option<Uuid>,
    pub company_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<RequestForQuotation> for RequestForQuotationResponseDto {
    fn from(entity: RequestForQuotation) -> Self {
        Self {
            id: entity.id,
            rfq_number: entity.rfq_number,
            material_request_id: entity.material_request_id,
            company_id: entity.company_id,
            status: entity.status,
            rfq_date: entity.rfq_date,
            response_due: entity.response_due,
            metadata: entity.metadata,
        }
    }
}

impl From<RequestForQuotation> for RequestForQuotationSummaryDto {
    fn from(entity: RequestForQuotation) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            rfq_number: entity.rfq_number,
            material_request_id: entity.material_request_id,
            company_id: entity.company_id,
            created_at,
        }
    }
}

impl From<CreateRequestForQuotationDto> for RequestForQuotation {
    fn from(dto: CreateRequestForQuotationDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            rfq_number: dto.rfq_number,
            material_request_id: dto.material_request_id,
            company_id: dto.company_id,
            status: dto.status,
            rfq_date: dto.rfq_date,
            response_due: dto.response_due,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&RequestForQuotation> for RequestForQuotationResponseDto {
    fn from(entity: &RequestForQuotation) -> Self {
        Self {
            id: entity.id.clone(),
            rfq_number: entity.rfq_number.clone(),
            material_request_id: entity.material_request_id.clone(),
            company_id: entity.company_id.clone(),
            status: entity.status.clone(),
            rfq_date: entity.rfq_date.clone(),
            response_due: entity.response_due.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateRequestForQuotationDto> for RequestForQuotation {
    fn from_create_dto(dto: CreateRequestForQuotationDto) -> backbone_core::ServiceResult<Self> {
        Ok(RequestForQuotation::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateRequestForQuotationDto> for RequestForQuotation {
    fn apply_update(mut self, dto: UpdateRequestForQuotationDto) -> backbone_core::ServiceResult<Self> {
        self.rfq_number = dto.rfq_number;
        self.material_request_id = dto.material_request_id;
        self.company_id = dto.company_id;
        self.status = dto.status;
        self.rfq_date = dto.rfq_date;
        self.response_due = dto.response_due;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to RequestForQuotation here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
