//! SupplierQuotationItem DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::SupplierQuotationItem;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new SupplierQuotationItem
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSupplierQuotationItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "quotation_id")]
    pub quotation_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub rate: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "lead_time_days")]
    pub lead_time_days: Option<i32>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a SupplierQuotationItem
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSupplierQuotationItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "quotation_id")]
    pub quotation_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub rate: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "lead_time_days")]
    pub lead_time_days: Option<i32>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a SupplierQuotationItem
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSupplierQuotationItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "quotation_id")]
    pub quotation_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rate: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "lead_time_days")]
    pub lead_time_days: Option<i32>,
}

impl PatchSupplierQuotationItemDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.quotation_id.is_some() || self.item_id.is_some() || self.quantity.is_some() || self.rate.is_some() || self.lead_time_days.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for SupplierQuotationItem entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SupplierQuotationItemResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub quotation_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub rate: Decimal,
    pub lead_time_days: Option<i32>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for SupplierQuotationItem entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SupplierQuotationItemListResponseDto {
    /// List of items
    pub items: Vec<SupplierQuotationItemResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SupplierQuotationItemListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SupplierQuotationItemResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SupplierQuotationItemSummaryDto {
    pub id: Uuid,
    pub quotation_id: Uuid,
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<SupplierQuotationItem> for SupplierQuotationItemResponseDto {
    fn from(entity: SupplierQuotationItem) -> Self {
        Self {
            id: entity.id,
            quotation_id: entity.quotation_id,
            item_id: entity.item_id,
            quantity: entity.quantity,
            rate: entity.rate,
            lead_time_days: entity.lead_time_days,
            metadata: entity.metadata,
        }
    }
}

impl From<SupplierQuotationItem> for SupplierQuotationItemSummaryDto {
    fn from(entity: SupplierQuotationItem) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            quotation_id: entity.quotation_id,
            item_id: entity.item_id,
            quantity: entity.quantity,
            created_at,
        }
    }
}

impl From<CreateSupplierQuotationItemDto> for SupplierQuotationItem {
    fn from(dto: CreateSupplierQuotationItemDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            quotation_id: dto.quotation_id,
            item_id: dto.item_id,
            quantity: dto.quantity,
            rate: dto.rate,
            lead_time_days: dto.lead_time_days,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&SupplierQuotationItem> for SupplierQuotationItemResponseDto {
    fn from(entity: &SupplierQuotationItem) -> Self {
        Self {
            id: entity.id.clone(),
            quotation_id: entity.quotation_id.clone(),
            item_id: entity.item_id.clone(),
            quantity: entity.quantity.clone(),
            rate: entity.rate.clone(),
            lead_time_days: entity.lead_time_days.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSupplierQuotationItemDto> for SupplierQuotationItem {
    fn from_create_dto(dto: CreateSupplierQuotationItemDto) -> backbone_core::ServiceResult<Self> {
        Ok(SupplierQuotationItem::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSupplierQuotationItemDto> for SupplierQuotationItem {
    fn apply_update(mut self, dto: UpdateSupplierQuotationItemDto) -> backbone_core::ServiceResult<Self> {
        self.quotation_id = dto.quotation_id;
        self.item_id = dto.item_id;
        self.quantity = dto.quantity;
        self.rate = dto.rate;
        self.lead_time_days = dto.lead_time_days;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to SupplierQuotationItem here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
