//! Domain policy for MaterialRequestItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::MaterialRequestItem;

/// Domain policy for MaterialRequestItem — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<MaterialRequestItem>` in the `// <<< CUSTOM` zone.
pub type MaterialRequestItemDomainPolicy = PermitAllPolicy<MaterialRequestItem>;

// <<< CUSTOM
// END CUSTOM
