//! Domain policy for SupplierQuotationItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::SupplierQuotationItem;

/// Domain policy for SupplierQuotationItem — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<SupplierQuotationItem>` in the `// <<< CUSTOM` zone.
pub type SupplierQuotationItemDomainPolicy = PermitAllPolicy<SupplierQuotationItem>;

// <<< CUSTOM
// END CUSTOM
