//! Domain policy for SupplierQuotation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::SupplierQuotation;

/// Domain policy for SupplierQuotation — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<SupplierQuotation>` in the `// <<< CUSTOM` zone.
pub type SupplierQuotationDomainPolicy = PermitAllPolicy<SupplierQuotation>;

// <<< CUSTOM
// END CUSTOM
