//! Application service for MaterialRequest entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `material_request_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMaterialRequestDto, UpdateMaterialRequestDto};
use crate::domain::entity::MaterialRequest;
use crate::infrastructure::persistence::MaterialRequestRepository;

/// Application service for MaterialRequest entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `material_request_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MaterialRequestServiceCustom {
///     inner: Arc<MaterialRequestService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MaterialRequestService = GenericCrudService<
    MaterialRequest,
    CreateMaterialRequestDto,
    UpdateMaterialRequestDto,
    MaterialRequestRepository,
>;

// <<< CUSTOM
// END CUSTOM
