//! Application service for PurchaseAgreementLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `purchase_agreement_line_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePurchaseAgreementLineDto, UpdatePurchaseAgreementLineDto};
use crate::domain::entity::PurchaseAgreementLine;
use crate::infrastructure::persistence::PurchaseAgreementLineRepository;

/// Application service for PurchaseAgreementLine entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `purchase_agreement_line_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PurchaseAgreementLineServiceCustom {
///     inner: Arc<PurchaseAgreementLineService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PurchaseAgreementLineService = GenericCrudService<
    PurchaseAgreementLine,
    CreatePurchaseAgreementLineDto,
    UpdatePurchaseAgreementLineDto,
    PurchaseAgreementLineRepository,
>;

// <<< CUSTOM
// END CUSTOM
