//! Application service for PurchaseCompanySetting entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `purchase_company_setting_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePurchaseCompanySettingDto, UpdatePurchaseCompanySettingDto};
use crate::domain::entity::PurchaseCompanySetting;
use crate::infrastructure::persistence::PurchaseCompanySettingRepository;

/// Application service for PurchaseCompanySetting entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `purchase_company_setting_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PurchaseCompanySettingServiceCustom {
///     inner: Arc<PurchaseCompanySettingService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PurchaseCompanySettingService = GenericCrudService<
    PurchaseCompanySetting,
    CreatePurchaseCompanySettingDto,
    UpdatePurchaseCompanySettingDto,
    PurchaseCompanySettingRepository,
>;

// <<< CUSTOM
// END CUSTOM
