//! Application service for RequestForQuotation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `request_for_quotation_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateRequestForQuotationDto, UpdateRequestForQuotationDto};
use crate::domain::entity::RequestForQuotation;
use crate::infrastructure::persistence::RequestForQuotationRepository;

/// Application service for RequestForQuotation entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `request_for_quotation_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct RequestForQuotationServiceCustom {
///     inner: Arc<RequestForQuotationService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type RequestForQuotationService = GenericCrudService<
    RequestForQuotation,
    CreateRequestForQuotationDto,
    UpdateRequestForQuotationDto,
    RequestForQuotationRepository,
>;

// <<< CUSTOM
// END CUSTOM
