//! Application service for RfqItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `rfq_item_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateRfqItemDto, UpdateRfqItemDto};
use crate::domain::entity::RfqItem;
use crate::infrastructure::persistence::RfqItemRepository;

/// Application service for RfqItem entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `rfq_item_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct RfqItemServiceCustom {
///     inner: Arc<RfqItemService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type RfqItemService = GenericCrudService<
    RfqItem,
    CreateRfqItemDto,
    UpdateRfqItemDto,
    RfqItemRepository,
>;

// <<< CUSTOM
// END CUSTOM
