-- PurchaseAgreement Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the buying.purchase_agreements table.
-- Customize this file to add your initial data.

-- INSERT INTO buying.purchase_agreements (
--     id,
--     agreement_number,
--     agreement_kind,
--     status,
--     company_id,
--     supplier_id,
--     currency,
--     date_start,
--     date_end,
--     notes,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO buying.purchase_agreements (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

