-- PurchaseOrder Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the buying.purchase_orders table.
-- Customize this file to add your initial data.

-- INSERT INTO buying.purchase_orders (
--     id,
--     po_number,
--     supplier_quotation_id,
--     order_kind,
--     company_id,
--     branch_id,
--     supplier_id,
--     status,
--     order_date,
--     schedule_date,
--     currency,
--     subtotal,
--     tax_rate,
--     tax_amount,
--     total,
--     notes,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO buying.purchase_orders (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

