-- PurchaseCompanySetting Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the buying.purchase_company_settings table.
-- Customize this file to add your initial data.

-- INSERT INTO buying.purchase_company_settings (
--     id,
--     company_id,
--     double_validation,
--     double_validation_amount,
--     company_currency,
--     send_reminder,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO buying.purchase_company_settings (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

