-- SupplierReminderSetting Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the buying.supplier_reminder_settings table.
-- Customize this file to add your initial data.

-- INSERT INTO buying.supplier_reminder_settings (
--     id,
--     company_id,
--     supplier_id,
--     receipt_reminder_email,
--     reminder_days_before,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO buying.supplier_reminder_settings (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

