-- Migration: Create rfq_items table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS buying;

CREATE TABLE IF NOT EXISTS buying.rfq_items (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    rfq_id UUID NOT NULL,
    item_id UUID NOT NULL,
    quantity NUMERIC(18, 4) NOT NULL CHECK (quantity >= 0),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_rfq_items_rfq_id ON buying.rfq_items (rfq_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_rfq_items_metadata_gin ON buying.rfq_items USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_rfq_items_metadata_deleted_at ON buying.rfq_items ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_rfq_items_metadata_created_at ON buying.rfq_items ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_rfq_items_metadata_updated_at ON buying.rfq_items ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION buying.rfq_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS rfq_items_insert_audit ON buying.rfq_items;
CREATE TRIGGER rfq_items_insert_audit BEFORE INSERT ON buying.rfq_items
    FOR EACH ROW EXECUTE FUNCTION buying.rfq_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS rfq_items_update_audit ON buying.rfq_items;
CREATE TRIGGER rfq_items_update_audit BEFORE UPDATE ON buying.rfq_items
    FOR EACH ROW EXECUTE FUNCTION buying.rfq_items_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE buying.rfq_items ADD CONSTRAINT fk_rfq_items_rfq_id FOREIGN KEY (rfq_id) REFERENCES buying.request_for_quotations (id);
