-- Migration: Create supplier_reminder_settings table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS buying;

CREATE TABLE IF NOT EXISTS buying.supplier_reminder_settings (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    supplier_id UUID NOT NULL,
    receipt_reminder_email BOOLEAN NOT NULL DEFAULT TRUE,
    reminder_days_before INTEGER NOT NULL DEFAULT 1,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_supplier_reminder_settings_company_id_supplier_id ON buying.supplier_reminder_settings (company_id, supplier_id) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_supplier_reminder_settings_metadata_gin ON buying.supplier_reminder_settings USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_supplier_reminder_settings_metadata_deleted_at ON buying.supplier_reminder_settings ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_supplier_reminder_settings_metadata_created_at ON buying.supplier_reminder_settings ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_supplier_reminder_settings_metadata_updated_at ON buying.supplier_reminder_settings ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION buying.supplier_reminder_settings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS supplier_reminder_settings_insert_audit ON buying.supplier_reminder_settings;
CREATE TRIGGER supplier_reminder_settings_insert_audit BEFORE INSERT ON buying.supplier_reminder_settings
    FOR EACH ROW EXECUTE FUNCTION buying.supplier_reminder_settings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS supplier_reminder_settings_update_audit ON buying.supplier_reminder_settings;
CREATE TRIGGER supplier_reminder_settings_update_audit BEFORE UPDATE ON buying.supplier_reminder_settings
    FOR EACH ROW EXECUTE FUNCTION buying.supplier_reminder_settings_audit_timestamp();
