-- Migration: Create purchase_company_settings table
-- Generated by metaphor-schema

-- Create double_validation enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'double_validation') THEN
        CREATE TYPE double_validation AS ENUM ('one_step', 'two_step');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS buying;

CREATE TABLE IF NOT EXISTS buying.purchase_company_settings (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    double_validation double_validation NOT NULL DEFAULT 'one_step',
    double_validation_amount NUMERIC(18, 2) NOT NULL DEFAULT 5000 CHECK (double_validation_amount >= 0),
    company_currency TEXT NOT NULL DEFAULT 'IDR',
    send_reminder BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_purchase_company_settings_company_id ON buying.purchase_company_settings (company_id) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_purchase_company_settings_metadata_gin ON buying.purchase_company_settings USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_purchase_company_settings_metadata_deleted_at ON buying.purchase_company_settings ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_purchase_company_settings_metadata_created_at ON buying.purchase_company_settings ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_purchase_company_settings_metadata_updated_at ON buying.purchase_company_settings ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION buying.purchase_company_settings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS purchase_company_settings_insert_audit ON buying.purchase_company_settings;
CREATE TRIGGER purchase_company_settings_insert_audit BEFORE INSERT ON buying.purchase_company_settings
    FOR EACH ROW EXECUTE FUNCTION buying.purchase_company_settings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS purchase_company_settings_update_audit ON buying.purchase_company_settings;
CREATE TRIGGER purchase_company_settings_update_audit BEFORE UPDATE ON buying.purchase_company_settings
    FOR EACH ROW EXECUTE FUNCTION buying.purchase_company_settings_audit_timestamp();
