-- Audit Triggers Migration for buying module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: MaterialRequest (buying.material_requests)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION buying.material_requests_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS material_requests_insert_audit ON buying.material_requests;
CREATE TRIGGER material_requests_insert_audit BEFORE INSERT ON buying.material_requests
    FOR EACH ROW EXECUTE FUNCTION buying.material_requests_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS material_requests_update_audit ON buying.material_requests;
CREATE TRIGGER material_requests_update_audit BEFORE UPDATE ON buying.material_requests
    FOR EACH ROW EXECUTE FUNCTION buying.material_requests_audit_timestamp();

-- ==============================================================================
-- Table: MaterialRequestItem (buying.material_request_items)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION buying.material_request_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS material_request_items_insert_audit ON buying.material_request_items;
CREATE TRIGGER material_request_items_insert_audit BEFORE INSERT ON buying.material_request_items
    FOR EACH ROW EXECUTE FUNCTION buying.material_request_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS material_request_items_update_audit ON buying.material_request_items;
CREATE TRIGGER material_request_items_update_audit BEFORE UPDATE ON buying.material_request_items
    FOR EACH ROW EXECUTE FUNCTION buying.material_request_items_audit_timestamp();

-- ==============================================================================
-- Table: PurchaseOrder (buying.purchase_orders)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION buying.purchase_orders_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS purchase_orders_insert_audit ON buying.purchase_orders;
CREATE TRIGGER purchase_orders_insert_audit BEFORE INSERT ON buying.purchase_orders
    FOR EACH ROW EXECUTE FUNCTION buying.purchase_orders_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS purchase_orders_update_audit ON buying.purchase_orders;
CREATE TRIGGER purchase_orders_update_audit BEFORE UPDATE ON buying.purchase_orders
    FOR EACH ROW EXECUTE FUNCTION buying.purchase_orders_audit_timestamp();

-- ==============================================================================
-- Table: PurchaseOrderItem (buying.purchase_order_items)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION buying.purchase_order_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS purchase_order_items_insert_audit ON buying.purchase_order_items;
CREATE TRIGGER purchase_order_items_insert_audit BEFORE INSERT ON buying.purchase_order_items
    FOR EACH ROW EXECUTE FUNCTION buying.purchase_order_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS purchase_order_items_update_audit ON buying.purchase_order_items;
CREATE TRIGGER purchase_order_items_update_audit BEFORE UPDATE ON buying.purchase_order_items
    FOR EACH ROW EXECUTE FUNCTION buying.purchase_order_items_audit_timestamp();

-- ==============================================================================
-- Table: RequestForQuotation (buying.request_for_quotations)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION buying.request_for_quotations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS request_for_quotations_insert_audit ON buying.request_for_quotations;
CREATE TRIGGER request_for_quotations_insert_audit BEFORE INSERT ON buying.request_for_quotations
    FOR EACH ROW EXECUTE FUNCTION buying.request_for_quotations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS request_for_quotations_update_audit ON buying.request_for_quotations;
CREATE TRIGGER request_for_quotations_update_audit BEFORE UPDATE ON buying.request_for_quotations
    FOR EACH ROW EXECUTE FUNCTION buying.request_for_quotations_audit_timestamp();

-- ==============================================================================
-- Table: RfqItem (buying.rfq_items)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION buying.rfq_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS rfq_items_insert_audit ON buying.rfq_items;
CREATE TRIGGER rfq_items_insert_audit BEFORE INSERT ON buying.rfq_items
    FOR EACH ROW EXECUTE FUNCTION buying.rfq_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS rfq_items_update_audit ON buying.rfq_items;
CREATE TRIGGER rfq_items_update_audit BEFORE UPDATE ON buying.rfq_items
    FOR EACH ROW EXECUTE FUNCTION buying.rfq_items_audit_timestamp();

-- ==============================================================================
-- Table: RfqSupplier (buying.rfq_suppliers)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION buying.rfq_suppliers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS rfq_suppliers_insert_audit ON buying.rfq_suppliers;
CREATE TRIGGER rfq_suppliers_insert_audit BEFORE INSERT ON buying.rfq_suppliers
    FOR EACH ROW EXECUTE FUNCTION buying.rfq_suppliers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS rfq_suppliers_update_audit ON buying.rfq_suppliers;
CREATE TRIGGER rfq_suppliers_update_audit BEFORE UPDATE ON buying.rfq_suppliers
    FOR EACH ROW EXECUTE FUNCTION buying.rfq_suppliers_audit_timestamp();

-- ==============================================================================
-- Table: SupplierQuotation (buying.supplier_quotations)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION buying.supplier_quotations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS supplier_quotations_insert_audit ON buying.supplier_quotations;
CREATE TRIGGER supplier_quotations_insert_audit BEFORE INSERT ON buying.supplier_quotations
    FOR EACH ROW EXECUTE FUNCTION buying.supplier_quotations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS supplier_quotations_update_audit ON buying.supplier_quotations;
CREATE TRIGGER supplier_quotations_update_audit BEFORE UPDATE ON buying.supplier_quotations
    FOR EACH ROW EXECUTE FUNCTION buying.supplier_quotations_audit_timestamp();

-- ==============================================================================
-- Table: SupplierQuotationItem (buying.supplier_quotation_items)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION buying.supplier_quotation_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS supplier_quotation_items_insert_audit ON buying.supplier_quotation_items;
CREATE TRIGGER supplier_quotation_items_insert_audit BEFORE INSERT ON buying.supplier_quotation_items
    FOR EACH ROW EXECUTE FUNCTION buying.supplier_quotation_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS supplier_quotation_items_update_audit ON buying.supplier_quotation_items;
CREATE TRIGGER supplier_quotation_items_update_audit BEFORE UPDATE ON buying.supplier_quotation_items
    FOR EACH ROW EXECUTE FUNCTION buying.supplier_quotation_items_audit_timestamp();

