-- Migration: Create purchase_agreements table
-- Generated by metaphor-schema

-- Create agreement_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'agreement_kind') THEN
        CREATE TYPE agreement_kind AS ENUM ('blanket');
    END IF;
END
$$;

-- Create purchase_agreement_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'purchase_agreement_status') THEN
        CREATE TYPE purchase_agreement_status AS ENUM ('draft', 'open', 'done', 'cancelled');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS buying;

CREATE TABLE IF NOT EXISTS buying.purchase_agreements (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    agreement_number TEXT NOT NULL,
    agreement_kind agreement_kind NOT NULL DEFAULT 'blanket',
    status purchase_agreement_status NOT NULL DEFAULT 'draft',
    company_id UUID NOT NULL,
    supplier_id UUID NOT NULL,
    currency TEXT NOT NULL DEFAULT 'IDR',
    date_start DATE,
    date_end DATE,
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_purchase_agreements_agreement_number ON buying.purchase_agreements (agreement_number) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_purchase_agreements_company_id_supplier_id_status ON buying.purchase_agreements (company_id, supplier_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_purchase_agreements_metadata_gin ON buying.purchase_agreements USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_purchase_agreements_metadata_deleted_at ON buying.purchase_agreements ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_purchase_agreements_metadata_created_at ON buying.purchase_agreements ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_purchase_agreements_metadata_updated_at ON buying.purchase_agreements ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION buying.purchase_agreements_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS purchase_agreements_insert_audit ON buying.purchase_agreements;
CREATE TRIGGER purchase_agreements_insert_audit BEFORE INSERT ON buying.purchase_agreements
    FOR EACH ROW EXECUTE FUNCTION buying.purchase_agreements_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS purchase_agreements_update_audit ON buying.purchase_agreements;
CREATE TRIGGER purchase_agreements_update_audit BEFORE UPDATE ON buying.purchase_agreements
    FOR EACH ROW EXECUTE FUNCTION buying.purchase_agreements_audit_timestamp();
