-- Company RLS fence for buying module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for buying.material_requests
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE buying.material_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE buying.material_requests FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS material_requests_company_isolation ON buying.material_requests;
CREATE POLICY material_requests_company_isolation ON buying.material_requests
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for buying.purchase_orders
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE buying.purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE buying.purchase_orders FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS purchase_orders_company_isolation ON buying.purchase_orders;
CREATE POLICY purchase_orders_company_isolation ON buying.purchase_orders
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for buying.request_for_quotations
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE buying.request_for_quotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE buying.request_for_quotations FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS request_for_quotations_company_isolation ON buying.request_for_quotations;
CREATE POLICY request_for_quotations_company_isolation ON buying.request_for_quotations
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for buying.supplier_quotations
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE buying.supplier_quotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE buying.supplier_quotations FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS supplier_quotations_company_isolation ON buying.supplier_quotations;
CREATE POLICY supplier_quotations_company_isolation ON buying.supplier_quotations
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

