-- Migration: Create supplier_prices table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS buying;

CREATE TABLE IF NOT EXISTS buying.supplier_prices (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    supplier_id UUID NOT NULL,
    item_id UUID NOT NULL,
    price NUMERIC(18, 2) NOT NULL,
    currency TEXT NOT NULL DEFAULT 'IDR',
    agreement_id UUID NOT NULL,
    agreement_line_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_supplier_prices_company_id_supplier_id_item_id_agreement_line_id ON buying.supplier_prices (company_id, supplier_id, item_id, agreement_line_id) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_supplier_prices_agreement_id ON buying.supplier_prices (agreement_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_supplier_prices_metadata_gin ON buying.supplier_prices USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_supplier_prices_metadata_deleted_at ON buying.supplier_prices ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_supplier_prices_metadata_created_at ON buying.supplier_prices ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_supplier_prices_metadata_updated_at ON buying.supplier_prices ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION buying.supplier_prices_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS supplier_prices_insert_audit ON buying.supplier_prices;
CREATE TRIGGER supplier_prices_insert_audit BEFORE INSERT ON buying.supplier_prices
    FOR EACH ROW EXECUTE FUNCTION buying.supplier_prices_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS supplier_prices_update_audit ON buying.supplier_prices;
CREATE TRIGGER supplier_prices_update_audit BEFORE UPDATE ON buying.supplier_prices
    FOR EACH ROW EXECUTE FUNCTION buying.supplier_prices_audit_timestamp();
