//! Event handler trait for MaterialRequestItem events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MaterialRequestItemEvent;

/// Event handler for MaterialRequestItem events.
/// Implement this trait to react to MaterialRequestItem lifecycle events.
pub trait MaterialRequestItemEventHandler: EventHandler<MaterialRequestItemEvent> {}
