//! Domain events for MaterialRequestItem entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MaterialRequestItem;

/// Domain events for MaterialRequestItem — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MaterialRequestItem>)` variant.
pub type MaterialRequestItemEvent = CrudEvent<MaterialRequestItem>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MaterialRequestItem events.
pub type MaterialRequestItemEventPublisher = Arc<dyn CrudEventPublisher<MaterialRequestItem> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMaterialRequestItemEventPublisher = NoOpCrudEventPublisher<MaterialRequestItem>;
