//! Domain events for MaterialRequest entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MaterialRequest;

/// Domain events for MaterialRequest — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MaterialRequest>)` variant.
pub type MaterialRequestEvent = CrudEvent<MaterialRequest>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MaterialRequest events.
pub type MaterialRequestEventPublisher = Arc<dyn CrudEventPublisher<MaterialRequest> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMaterialRequestEventPublisher = NoOpCrudEventPublisher<MaterialRequest>;
