//! Event handler trait for MaterialRequest events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MaterialRequestEvent;

/// Event handler for MaterialRequest events.
/// Implement this trait to react to MaterialRequest lifecycle events.
pub trait MaterialRequestEventHandler: EventHandler<MaterialRequestEvent> {}
