//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod material_request_events;
pub mod material_request_event_handlers;
pub mod material_request_item_events;
pub mod material_request_item_event_handlers;
pub mod purchase_order_events;
pub mod purchase_order_event_handlers;
pub mod purchase_order_item_events;
pub mod purchase_order_item_event_handlers;
pub mod request_for_quotation_events;
pub mod request_for_quotation_event_handlers;
pub mod rfq_item_events;
pub mod rfq_item_event_handlers;
pub mod rfq_supplier_events;
pub mod rfq_supplier_event_handlers;
pub mod supplier_quotation_events;
pub mod supplier_quotation_event_handlers;
pub mod supplier_quotation_item_events;
pub mod supplier_quotation_item_event_handlers;

pub use material_request_events::{MaterialRequestEvent, MaterialRequestEventPublisher, NoopMaterialRequestEventPublisher};
pub use material_request_event_handlers::MaterialRequestEventHandler;
pub use material_request_item_events::{MaterialRequestItemEvent, MaterialRequestItemEventPublisher, NoopMaterialRequestItemEventPublisher};
pub use material_request_item_event_handlers::MaterialRequestItemEventHandler;
pub use purchase_order_events::{PurchaseOrderEvent, PurchaseOrderEventPublisher, NoopPurchaseOrderEventPublisher};
pub use purchase_order_event_handlers::PurchaseOrderEventHandler;
pub use purchase_order_item_events::{PurchaseOrderItemEvent, PurchaseOrderItemEventPublisher, NoopPurchaseOrderItemEventPublisher};
pub use purchase_order_item_event_handlers::PurchaseOrderItemEventHandler;
pub use request_for_quotation_events::{RequestForQuotationEvent, RequestForQuotationEventPublisher, NoopRequestForQuotationEventPublisher};
pub use request_for_quotation_event_handlers::RequestForQuotationEventHandler;
pub use rfq_item_events::{RfqItemEvent, RfqItemEventPublisher, NoopRfqItemEventPublisher};
pub use rfq_item_event_handlers::RfqItemEventHandler;
pub use rfq_supplier_events::{RfqSupplierEvent, RfqSupplierEventPublisher, NoopRfqSupplierEventPublisher};
pub use rfq_supplier_event_handlers::RfqSupplierEventHandler;
pub use supplier_quotation_events::{SupplierQuotationEvent, SupplierQuotationEventPublisher, NoopSupplierQuotationEventPublisher};
pub use supplier_quotation_event_handlers::SupplierQuotationEventHandler;
pub use supplier_quotation_item_events::{SupplierQuotationItemEvent, SupplierQuotationItemEventPublisher, NoopSupplierQuotationItemEventPublisher};
pub use supplier_quotation_item_event_handlers::SupplierQuotationItemEventHandler;

// <<< CUSTOM
// END CUSTOM
