//! Event handler trait for PurchaseAgreement events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PurchaseAgreementEvent;

/// Event handler for PurchaseAgreement events.
/// Implement this trait to react to PurchaseAgreement lifecycle events.
pub trait PurchaseAgreementEventHandler: EventHandler<PurchaseAgreementEvent> {}
