//! Domain events for PurchaseAgreement entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PurchaseAgreement;

/// Domain events for PurchaseAgreement — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PurchaseAgreement>)` variant.
pub type PurchaseAgreementEvent = CrudEvent<PurchaseAgreement>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PurchaseAgreement events.
pub type PurchaseAgreementEventPublisher = Arc<dyn CrudEventPublisher<PurchaseAgreement> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPurchaseAgreementEventPublisher = NoOpCrudEventPublisher<PurchaseAgreement>;
