//! Event handler trait for PurchaseCompanySetting events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PurchaseCompanySettingEvent;

/// Event handler for PurchaseCompanySetting events.
/// Implement this trait to react to PurchaseCompanySetting lifecycle events.
pub trait PurchaseCompanySettingEventHandler: EventHandler<PurchaseCompanySettingEvent> {}
