//! Domain events for PurchaseAgreementLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PurchaseAgreementLine;

/// Domain events for PurchaseAgreementLine — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PurchaseAgreementLine>)` variant.
pub type PurchaseAgreementLineEvent = CrudEvent<PurchaseAgreementLine>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PurchaseAgreementLine events.
pub type PurchaseAgreementLineEventPublisher = Arc<dyn CrudEventPublisher<PurchaseAgreementLine> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPurchaseAgreementLineEventPublisher = NoOpCrudEventPublisher<PurchaseAgreementLine>;
