//! Domain events for RfqItem entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::RfqItem;

/// Domain events for RfqItem — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<RfqItem>)` variant.
pub type RfqItemEvent = CrudEvent<RfqItem>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for RfqItem events.
pub type RfqItemEventPublisher = Arc<dyn CrudEventPublisher<RfqItem> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopRfqItemEventPublisher = NoOpCrudEventPublisher<RfqItem>;
