//! Event handler trait for RfqSupplier events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::RfqSupplierEvent;

/// Event handler for RfqSupplier events.
/// Implement this trait to react to RfqSupplier lifecycle events.
pub trait RfqSupplierEventHandler: EventHandler<RfqSupplierEvent> {}
