//! Domain events for RfqSupplier entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::RfqSupplier;

/// Domain events for RfqSupplier — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<RfqSupplier>)` variant.
pub type RfqSupplierEvent = CrudEvent<RfqSupplier>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for RfqSupplier events.
pub type RfqSupplierEventPublisher = Arc<dyn CrudEventPublisher<RfqSupplier> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopRfqSupplierEventPublisher = NoOpCrudEventPublisher<RfqSupplier>;
