//! Event handler trait for RfqItem events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::RfqItemEvent;

/// Event handler for RfqItem events.
/// Implement this trait to react to RfqItem lifecycle events.
pub trait RfqItemEventHandler: EventHandler<RfqItemEvent> {}
