//! Domain events for SupplierQuotation entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SupplierQuotation;

/// Domain events for SupplierQuotation — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SupplierQuotation>)` variant.
pub type SupplierQuotationEvent = CrudEvent<SupplierQuotation>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SupplierQuotation events.
pub type SupplierQuotationEventPublisher = Arc<dyn CrudEventPublisher<SupplierQuotation> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSupplierQuotationEventPublisher = NoOpCrudEventPublisher<SupplierQuotation>;
