//! Domain events for SupplierQuotationItem entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SupplierQuotationItem;

/// Domain events for SupplierQuotationItem — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SupplierQuotationItem>)` variant.
pub type SupplierQuotationItemEvent = CrudEvent<SupplierQuotationItem>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SupplierQuotationItem events.
pub type SupplierQuotationItemEventPublisher = Arc<dyn CrudEventPublisher<SupplierQuotationItem> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSupplierQuotationItemEventPublisher = NoOpCrudEventPublisher<SupplierQuotationItem>;
