//! Event handler trait for SupplierReminderSetting events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SupplierReminderSettingEvent;

/// Event handler for SupplierReminderSetting events.
/// Implement this trait to react to SupplierReminderSetting lifecycle events.
pub trait SupplierReminderSettingEventHandler: EventHandler<SupplierReminderSettingEvent> {}
