//! Event handler trait for SupplierQuotation events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SupplierQuotationEvent;

/// Event handler for SupplierQuotation events.
/// Implement this trait to react to SupplierQuotation lifecycle events.
pub trait SupplierQuotationEventHandler: EventHandler<SupplierQuotationEvent> {}
