//! Event subscriber type aliases for Buying module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::MaterialRequestEvent;
use crate::domain::event::MaterialRequestItemEvent;
use crate::domain::event::PurchaseOrderEvent;
use crate::domain::event::PurchaseOrderItemEvent;
use crate::domain::event::RequestForQuotationEvent;
use crate::domain::event::RfqItemEvent;
use crate::domain::event::RfqSupplierEvent;
use crate::domain::event::SupplierQuotationEvent;
use crate::domain::event::SupplierQuotationItemEvent;

/// Subscriber for MaterialRequest events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type MaterialRequestEventSubscriber = GenericEventSubscriber<MaterialRequestEvent>;

/// Subscriber for MaterialRequestItem events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type MaterialRequestItemEventSubscriber = GenericEventSubscriber<MaterialRequestItemEvent>;

/// Subscriber for PurchaseOrder events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PurchaseOrderEventSubscriber = GenericEventSubscriber<PurchaseOrderEvent>;

/// Subscriber for PurchaseOrderItem events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PurchaseOrderItemEventSubscriber = GenericEventSubscriber<PurchaseOrderItemEvent>;

/// Subscriber for RequestForQuotation events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type RequestForQuotationEventSubscriber = GenericEventSubscriber<RequestForQuotationEvent>;

/// Subscriber for RfqItem events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type RfqItemEventSubscriber = GenericEventSubscriber<RfqItemEvent>;

/// Subscriber for RfqSupplier events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type RfqSupplierEventSubscriber = GenericEventSubscriber<RfqSupplierEvent>;

/// Subscriber for SupplierQuotation events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type SupplierQuotationEventSubscriber = GenericEventSubscriber<SupplierQuotationEvent>;

/// Subscriber for SupplierQuotationItem events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type SupplierQuotationItemEventSubscriber = GenericEventSubscriber<SupplierQuotationItemEvent>;

// <<< CUSTOM
// END CUSTOM
