//! Buying Event Subscriptions
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Cross-module event subscriptions. Each entity subscriber is a type alias
//! over `GenericEventSubscriber` from backbone-messaging.

pub mod handlers;
pub mod registry;

pub use handlers::*;
pub use registry::SubscriptionRegistry;

pub use handlers::MaterialRequestEventSubscriber;
pub use handlers::MaterialRequestItemEventSubscriber;
pub use handlers::PurchaseOrderEventSubscriber;
pub use handlers::PurchaseOrderItemEventSubscriber;
pub use handlers::RequestForQuotationEventSubscriber;
pub use handlers::RfqItemEventSubscriber;
pub use handlers::RfqSupplierEventSubscriber;
pub use handlers::SupplierQuotationEventSubscriber;
pub use handlers::SupplierQuotationItemEventSubscriber;
