//! MaterialRequestItem seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial MaterialRequestItem data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// MATERIALREQUESTITEM SEEDER
// ============================================================================

/// Seeder for material_request_item
pub struct SeedMaterialRequestItemSeeder;

impl SeedMaterialRequestItemSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedMaterialRequestItemSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedMaterialRequestItemSeeder {
    fn name(&self) -> &'static str {
        "SeedMaterialRequestItemSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if buying.material_request_items table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM buying.material_request_items")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/material_request_item_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM buying.material_request_items")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

