//! Database seeders for the buying module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides seed data for initial database setup.
//! Seeders can be run via the seeder binary or CLI.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

mod material_request_seeder;
mod material_request_item_seeder;
mod purchase_order_seeder;
mod purchase_order_item_seeder;
mod request_for_quotation_seeder;
mod rfq_item_seeder;
mod rfq_supplier_seeder;
mod supplier_quotation_seeder;
mod supplier_quotation_item_seeder;

pub use material_request_seeder::SeedMaterialRequestSeeder;
pub use material_request_item_seeder::SeedMaterialRequestItemSeeder;
pub use purchase_order_seeder::SeedPurchaseOrderSeeder;
pub use purchase_order_item_seeder::SeedPurchaseOrderItemSeeder;
pub use request_for_quotation_seeder::SeedRequestForQuotationSeeder;
pub use rfq_item_seeder::SeedRfqItemSeeder;
pub use rfq_supplier_seeder::SeedRfqSupplierSeeder;
pub use supplier_quotation_seeder::SeedSupplierQuotationSeeder;
pub use supplier_quotation_item_seeder::SeedSupplierQuotationItemSeeder;

// ============================================================================
// SEEDER TRAIT
// ============================================================================

/// Trait for database seeders
#[async_trait]
pub trait Seeder {
    /// Get the name of this seeder
    fn name(&self) -> &'static str;

    /// Get the order in which this seeder should run
    fn order(&self) -> i32;

    /// Check if this seeder should run (e.g., check if data already exists)
    async fn should_run(&self, pool: &PgPool) -> Result<bool>;

    /// Run the seeder
    async fn run(&self, pool: &PgPool) -> Result<()>;

    /// Rollback the seeder (optional)
    async fn rollback(&self, _pool: &PgPool) -> Result<()> {
        Ok(())
    }
}

// ============================================================================
// SEEDER TYPE
// ============================================================================

/// Type of seeder
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeederType {
    /// Reference data (required for application to function)
    Reference,
    /// Initial production data
    Production,
    /// Development/testing data
    Development,
    /// Test data (for automated tests)
    Test,
// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here.
}

// ============================================================================
// CUSTOM SEEDERS
// ============================================================================

// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here
// <<< CUSTOM SEEDERS END >>>
