//! PurchaseAgreementLine seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial PurchaseAgreementLine data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PURCHASEAGREEMENTLINE SEEDER
// ============================================================================

/// Seeder for purchase_agreement_line
pub struct SeedPurchaseAgreementLineSeeder;

impl SeedPurchaseAgreementLineSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPurchaseAgreementLineSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPurchaseAgreementLineSeeder {
    fn name(&self) -> &'static str {
        "SeedPurchaseAgreementLineSeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if buying.purchase_agreement_lines table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM buying.purchase_agreement_lines")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/purchase_agreement_line_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM buying.purchase_agreement_lines")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
