//! RequestForQuotation seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial RequestForQuotation data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// REQUESTFORQUOTATION SEEDER
// ============================================================================

/// Seeder for request_for_quotation
pub struct SeedRequestForQuotationSeeder;

impl SeedRequestForQuotationSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedRequestForQuotationSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedRequestForQuotationSeeder {
    fn name(&self) -> &'static str {
        "SeedRequestForQuotationSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if buying.request_for_quotations table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM buying.request_for_quotations")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/request_for_quotation_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM buying.request_for_quotations")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

