//! RfqItem seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial RfqItem data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// RFQITEM SEEDER
// ============================================================================

/// Seeder for rfq_item
pub struct SeedRfqItemSeeder;

impl SeedRfqItemSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedRfqItemSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedRfqItemSeeder {
    fn name(&self) -> &'static str {
        "SeedRfqItemSeeder"
    }

    fn order(&self) -> i32 {
        6
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if buying.rfq_items table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM buying.rfq_items")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/rfq_item_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM buying.rfq_items")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

