//! SupplierReminderSetting seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial SupplierReminderSetting data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SUPPLIERREMINDERSETTING SEEDER
// ============================================================================

/// Seeder for supplier_reminder_setting
pub struct SeedSupplierReminderSettingSeeder;

impl SeedSupplierReminderSettingSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedSupplierReminderSettingSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedSupplierReminderSettingSeeder {
    fn name(&self) -> &'static str {
        "SeedSupplierReminderSettingSeeder"
    }

    fn order(&self) -> i32 {
        13
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if buying.supplier_reminder_settings table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM buying.supplier_reminder_settings")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/supplier_reminder_setting_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM buying.supplier_reminder_settings")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
