//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod material_request_repository;
pub mod material_request_item_repository;
pub mod purchase_order_repository;
pub mod purchase_order_item_repository;
pub mod request_for_quotation_repository;
pub mod rfq_item_repository;
pub mod rfq_supplier_repository;
pub mod supplier_quotation_repository;
pub mod supplier_quotation_item_repository;

// Re-exports
pub use material_request_repository::{
    MaterialRequestRepository,
    MaterialRequestPaginationParams,
    MaterialRequestPaginatedResult,
    MaterialRequestFilter,
};
pub use material_request_item_repository::{
    MaterialRequestItemRepository,
    MaterialRequestItemPaginationParams,
    MaterialRequestItemPaginatedResult,
    MaterialRequestItemFilter,
};
pub use purchase_order_repository::{
    PurchaseOrderRepository,
    PurchaseOrderPaginationParams,
    PurchaseOrderPaginatedResult,
    PurchaseOrderFilter,
};
pub use purchase_order_item_repository::{
    PurchaseOrderItemRepository,
    PurchaseOrderItemPaginationParams,
    PurchaseOrderItemPaginatedResult,
    PurchaseOrderItemFilter,
};
pub use request_for_quotation_repository::{
    RequestForQuotationRepository,
    RequestForQuotationPaginationParams,
    RequestForQuotationPaginatedResult,
    RequestForQuotationFilter,
};
pub use rfq_item_repository::{
    RfqItemRepository,
    RfqItemPaginationParams,
    RfqItemPaginatedResult,
    RfqItemFilter,
};
pub use rfq_supplier_repository::{
    RfqSupplierRepository,
    RfqSupplierPaginationParams,
    RfqSupplierPaginatedResult,
    RfqSupplierFilter,
};
pub use supplier_quotation_repository::{
    SupplierQuotationRepository,
    SupplierQuotationPaginationParams,
    SupplierQuotationPaginatedResult,
    SupplierQuotationFilter,
};
pub use supplier_quotation_item_repository::{
    SupplierQuotationItemRepository,
    SupplierQuotationItemPaginationParams,
    SupplierQuotationItemPaginatedResult,
    SupplierQuotationItemFilter,
};
