//! Repository trait for PurchaseAgreement aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PurchaseAgreement aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PurchaseAgreement, AgreementKind, PurchaseAgreementStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PurchaseAgreementPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PurchaseAgreementPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PurchaseAgreementPaginatedResult {
    pub data: Vec<PurchaseAgreement>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PurchaseAgreementFilter {
    pub agreement_number: Option<String>,
    pub agreement_kind: Option<AgreementKind>,
    pub status: Option<PurchaseAgreementStatus>,
    pub company_id: Option<Uuid>,
    pub supplier_id: Option<Uuid>,
    pub currency: Option<String>,
    pub notes: Option<String>,
}

impl PurchaseAgreementFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.agreement_number.is_some() || self.agreement_kind.is_some() || self.status.is_some() || self.company_id.is_some() || self.supplier_id.is_some() || self.currency.is_some() || self.notes.is_some()
    }
}

/// Repository trait for PurchaseAgreement aggregate
///
/// This trait defines the persistence contract for PurchaseAgreement entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PurchaseAgreementRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new purchase_agreement entity
    async fn save(&self, entity: &PurchaseAgreement) -> Result<PurchaseAgreement>;

    /// Find purchase_agreement by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PurchaseAgreement>>;

    /// Find all purchase_agreement entities
    async fn find_all(&self) -> Result<Vec<PurchaseAgreement>>;

    /// Update purchase_agreement by ID
    async fn update(&self, id: &str, entity: &PurchaseAgreement) -> Result<Option<PurchaseAgreement>>;

    /// Delete purchase_agreement by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List purchase_agreement with pagination
    async fn list(&self, params: PurchaseAgreementPaginationParams) -> Result<PurchaseAgreementPaginatedResult>;

    /// List purchase_agreement with pagination and filters
    async fn list_with_filters(&self, params: PurchaseAgreementPaginationParams, filters: PurchaseAgreementFilter) -> Result<PurchaseAgreementPaginatedResult>;

    /// Count all purchase_agreement entities
    async fn count(&self) -> Result<u64>;

    /// Count purchase_agreement entities matching filters
    async fn count_with_filters(&self, filters: PurchaseAgreementFilter) -> Result<u64>;

    /// Check if purchase_agreement exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete purchase_agreement by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted purchase_agreement by ID
    async fn restore(&self, id: &str) -> Result<Option<PurchaseAgreement>>;

    /// List soft-deleted purchase_agreement entities
    async fn list_deleted(&self, params: PurchaseAgreementPaginationParams) -> Result<PurchaseAgreementPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save purchase_agreement entities
    async fn bulk_save(&self, entities: &[PurchaseAgreement]) -> Result<Vec<PurchaseAgreement>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
