//! Repository trait for PurchaseCompanySetting aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PurchaseCompanySetting aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PurchaseCompanySetting, DoubleValidation};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PurchaseCompanySettingPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PurchaseCompanySettingPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PurchaseCompanySettingPaginatedResult {
    pub data: Vec<PurchaseCompanySetting>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PurchaseCompanySettingFilter {
    pub company_id: Option<Uuid>,
    pub double_validation: Option<DoubleValidation>,
    pub company_currency: Option<String>,
    pub send_reminder: Option<bool>,
}

impl PurchaseCompanySettingFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.double_validation.is_some() || self.company_currency.is_some() || self.send_reminder.is_some()
    }
}

/// Repository trait for PurchaseCompanySetting aggregate
///
/// This trait defines the persistence contract for PurchaseCompanySetting entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PurchaseCompanySettingRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new purchase_company_setting entity
    async fn save(&self, entity: &PurchaseCompanySetting) -> Result<PurchaseCompanySetting>;

    /// Find purchase_company_setting by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PurchaseCompanySetting>>;

    /// Find all purchase_company_setting entities
    async fn find_all(&self) -> Result<Vec<PurchaseCompanySetting>>;

    /// Update purchase_company_setting by ID
    async fn update(&self, id: &str, entity: &PurchaseCompanySetting) -> Result<Option<PurchaseCompanySetting>>;

    /// Delete purchase_company_setting by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List purchase_company_setting with pagination
    async fn list(&self, params: PurchaseCompanySettingPaginationParams) -> Result<PurchaseCompanySettingPaginatedResult>;

    /// List purchase_company_setting with pagination and filters
    async fn list_with_filters(&self, params: PurchaseCompanySettingPaginationParams, filters: PurchaseCompanySettingFilter) -> Result<PurchaseCompanySettingPaginatedResult>;

    /// Count all purchase_company_setting entities
    async fn count(&self) -> Result<u64>;

    /// Count purchase_company_setting entities matching filters
    async fn count_with_filters(&self, filters: PurchaseCompanySettingFilter) -> Result<u64>;

    /// Check if purchase_company_setting exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete purchase_company_setting by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted purchase_company_setting by ID
    async fn restore(&self, id: &str) -> Result<Option<PurchaseCompanySetting>>;

    /// List soft-deleted purchase_company_setting entities
    async fn list_deleted(&self, params: PurchaseCompanySettingPaginationParams) -> Result<PurchaseCompanySettingPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save purchase_company_setting entities
    async fn bulk_save(&self, entities: &[PurchaseCompanySetting]) -> Result<Vec<PurchaseCompanySetting>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
