//! Repository trait for PurchaseOrder aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PurchaseOrder aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PurchaseOrder, OrderKind, PurchaseOrderStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PurchaseOrderPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PurchaseOrderPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PurchaseOrderPaginatedResult {
    pub data: Vec<PurchaseOrder>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PurchaseOrderFilter {
    pub po_number: Option<String>,
    pub supplier_quotation_id: Option<Uuid>,
    pub order_kind: Option<OrderKind>,
    pub company_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub supplier_id: Option<Uuid>,
    pub status: Option<PurchaseOrderStatus>,
    pub currency: Option<String>,
    pub notes: Option<String>,
}

impl PurchaseOrderFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.po_number.is_some() || self.supplier_quotation_id.is_some() || self.order_kind.is_some() || self.company_id.is_some() || self.branch_id.is_some() || self.supplier_id.is_some() || self.status.is_some() || self.currency.is_some() || self.notes.is_some()
    }
}

/// Repository trait for PurchaseOrder aggregate
///
/// This trait defines the persistence contract for PurchaseOrder entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PurchaseOrderRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new purchase_order entity
    async fn save(&self, entity: &PurchaseOrder) -> Result<PurchaseOrder>;

    /// Find purchase_order by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PurchaseOrder>>;

    /// Find all purchase_order entities
    async fn find_all(&self) -> Result<Vec<PurchaseOrder>>;

    /// Update purchase_order by ID
    async fn update(&self, id: &str, entity: &PurchaseOrder) -> Result<Option<PurchaseOrder>>;

    /// Delete purchase_order by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List purchase_order with pagination
    async fn list(&self, params: PurchaseOrderPaginationParams) -> Result<PurchaseOrderPaginatedResult>;

    /// List purchase_order with pagination and filters
    async fn list_with_filters(&self, params: PurchaseOrderPaginationParams, filters: PurchaseOrderFilter) -> Result<PurchaseOrderPaginatedResult>;

    /// Count all purchase_order entities
    async fn count(&self) -> Result<u64>;

    /// Count purchase_order entities matching filters
    async fn count_with_filters(&self, filters: PurchaseOrderFilter) -> Result<u64>;

    /// Check if purchase_order exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete purchase_order by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted purchase_order by ID
    async fn restore(&self, id: &str) -> Result<Option<PurchaseOrder>>;

    /// List soft-deleted purchase_order entities
    async fn list_deleted(&self, params: PurchaseOrderPaginationParams) -> Result<PurchaseOrderPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save purchase_order entities
    async fn bulk_save(&self, entities: &[PurchaseOrder]) -> Result<Vec<PurchaseOrder>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
