//! Repository trait for RfqSupplier aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the RfqSupplier aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::RfqSupplier;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RfqSupplierPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl RfqSupplierPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct RfqSupplierPaginatedResult {
    pub data: Vec<RfqSupplier>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RfqSupplierFilter {
    pub rfq_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub supplier_id: Option<Uuid>,
}

impl RfqSupplierFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.rfq_id.is_some() || self.company_id.is_some() || self.supplier_id.is_some()
    }
}

/// Repository trait for RfqSupplier aggregate
///
/// This trait defines the persistence contract for RfqSupplier entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait RfqSupplierRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new rfq_supplier entity
    async fn save(&self, entity: &RfqSupplier) -> Result<RfqSupplier>;

    /// Find rfq_supplier by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<RfqSupplier>>;

    /// Find all rfq_supplier entities
    async fn find_all(&self) -> Result<Vec<RfqSupplier>>;

    /// Update rfq_supplier by ID
    async fn update(&self, id: &str, entity: &RfqSupplier) -> Result<Option<RfqSupplier>>;

    /// Delete rfq_supplier by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List rfq_supplier with pagination
    async fn list(&self, params: RfqSupplierPaginationParams) -> Result<RfqSupplierPaginatedResult>;

    /// List rfq_supplier with pagination and filters
    async fn list_with_filters(&self, params: RfqSupplierPaginationParams, filters: RfqSupplierFilter) -> Result<RfqSupplierPaginatedResult>;

    /// Count all rfq_supplier entities
    async fn count(&self) -> Result<u64>;

    /// Count rfq_supplier entities matching filters
    async fn count_with_filters(&self, filters: RfqSupplierFilter) -> Result<u64>;

    /// Check if rfq_supplier exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete rfq_supplier by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted rfq_supplier by ID
    async fn restore(&self, id: &str) -> Result<Option<RfqSupplier>>;

    /// List soft-deleted rfq_supplier entities
    async fn list_deleted(&self, params: RfqSupplierPaginationParams) -> Result<RfqSupplierPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save rfq_supplier entities
    async fn bulk_save(&self, entities: &[RfqSupplier]) -> Result<Vec<RfqSupplier>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
