//! Repository trait for RfqItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the RfqItem aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::RfqItem;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RfqItemPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl RfqItemPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct RfqItemPaginatedResult {
    pub data: Vec<RfqItem>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RfqItemFilter {
    pub rfq_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
}

impl RfqItemFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.rfq_id.is_some() || self.item_id.is_some()
    }
}

/// Repository trait for RfqItem aggregate
///
/// This trait defines the persistence contract for RfqItem entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait RfqItemRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new rfq_item entity
    async fn save(&self, entity: &RfqItem) -> Result<RfqItem>;

    /// Find rfq_item by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<RfqItem>>;

    /// Find all rfq_item entities
    async fn find_all(&self) -> Result<Vec<RfqItem>>;

    /// Update rfq_item by ID
    async fn update(&self, id: &str, entity: &RfqItem) -> Result<Option<RfqItem>>;

    /// Delete rfq_item by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List rfq_item with pagination
    async fn list(&self, params: RfqItemPaginationParams) -> Result<RfqItemPaginatedResult>;

    /// List rfq_item with pagination and filters
    async fn list_with_filters(&self, params: RfqItemPaginationParams, filters: RfqItemFilter) -> Result<RfqItemPaginatedResult>;

    /// Count all rfq_item entities
    async fn count(&self) -> Result<u64>;

    /// Count rfq_item entities matching filters
    async fn count_with_filters(&self, filters: RfqItemFilter) -> Result<u64>;

    /// Check if rfq_item exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete rfq_item by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted rfq_item by ID
    async fn restore(&self, id: &str) -> Result<Option<RfqItem>>;

    /// List soft-deleted rfq_item entities
    async fn list_deleted(&self, params: RfqItemPaginationParams) -> Result<RfqItemPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save rfq_item entities
    async fn bulk_save(&self, entities: &[RfqItem]) -> Result<Vec<RfqItem>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
