//! Repository trait for SupplierPrice aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SupplierPrice aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::SupplierPrice;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SupplierPricePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SupplierPricePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SupplierPricePaginatedResult {
    pub data: Vec<SupplierPrice>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SupplierPriceFilter {
    pub company_id: Option<Uuid>,
    pub supplier_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub currency: Option<String>,
    pub agreement_id: Option<Uuid>,
    pub agreement_line_id: Option<Uuid>,
}

impl SupplierPriceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.supplier_id.is_some() || self.item_id.is_some() || self.currency.is_some() || self.agreement_id.is_some() || self.agreement_line_id.is_some()
    }
}

/// Repository trait for SupplierPrice aggregate
///
/// This trait defines the persistence contract for SupplierPrice entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SupplierPriceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new supplier_price entity
    async fn save(&self, entity: &SupplierPrice) -> Result<SupplierPrice>;

    /// Find supplier_price by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SupplierPrice>>;

    /// Find all supplier_price entities
    async fn find_all(&self) -> Result<Vec<SupplierPrice>>;

    /// Update supplier_price by ID
    async fn update(&self, id: &str, entity: &SupplierPrice) -> Result<Option<SupplierPrice>>;

    /// Delete supplier_price by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List supplier_price with pagination
    async fn list(&self, params: SupplierPricePaginationParams) -> Result<SupplierPricePaginatedResult>;

    /// List supplier_price with pagination and filters
    async fn list_with_filters(&self, params: SupplierPricePaginationParams, filters: SupplierPriceFilter) -> Result<SupplierPricePaginatedResult>;

    /// Count all supplier_price entities
    async fn count(&self) -> Result<u64>;

    /// Count supplier_price entities matching filters
    async fn count_with_filters(&self, filters: SupplierPriceFilter) -> Result<u64>;

    /// Check if supplier_price exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete supplier_price by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted supplier_price by ID
    async fn restore(&self, id: &str) -> Result<Option<SupplierPrice>>;

    /// List soft-deleted supplier_price entities
    async fn list_deleted(&self, params: SupplierPricePaginationParams) -> Result<SupplierPricePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save supplier_price entities
    async fn bulk_save(&self, entities: &[SupplierPrice]) -> Result<Vec<SupplierPrice>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
