//! Repository for MaterialRequestItem entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written MaterialRequestItem SQL (4-layer rule: services orchestrate, repos
//! hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<MaterialRequestItem, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::MaterialRequestItem;

/// Table name for MaterialRequestItem entities
pub const TABLE_NAME: &str = "buying.material_request_items";

/// Repository for MaterialRequestItem entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MaterialRequestItemRepository(
    backbone_orm::GenericCrudRepository<MaterialRequestItem, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for MaterialRequestItemRepository {
    type Target = backbone_orm::GenericCrudRepository<MaterialRequestItem, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MaterialRequestItemRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a material-request line insert writes.
pub struct NewMaterialRequestItemRow {
    pub id: Uuid,
    pub request_id: Uuid,
    pub item_id: Uuid,
    pub quantity: Decimal,
}

/// A requested line, as copied forward by the MR→RFQ funnel step.
pub struct RequestedLineRow {
    pub item_id: Uuid,
    pub quantity: Decimal,
}

/// Hand-written MaterialRequestItem SQL. Lives here (not in the write service) per the module's
/// 4-layer rule.
impl MaterialRequestItemRepository {
    /// Insert one requested line.
    ///
    /// Takes the CALLER'S connection so it commits with its header. The caller has already bound the
    /// company on it (`bind_company_on`) — don't re-bind here.
    pub async fn insert_item(
        &self,
        conn: &mut sqlx::PgConnection,
        l: &NewMaterialRequestItemRow,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            "INSERT INTO buying.material_request_items (id, request_id, item_id, quantity) VALUES ($1,$2,$3,$4)",
        )
        .bind(l.id).bind(l.request_id).bind(l.item_id).bind(l.quantity)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read a material request's lines for the MR→RFQ conversion. ID-only + `fetch_all_rows_scoped`:
    /// rides the caller's company scope, as in [`super::MaterialRequestRepository::fetch_source`].
    pub async fn fetch_lines(
        &self,
        pool: &PgPool,
        request_id: Uuid,
    ) -> Result<Vec<RequestedLineRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT item_id, quantity FROM buying.material_request_items
                   WHERE request_id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            ).bind(request_id),
        )
        .await?;
        Ok(rows.iter().map(|r| RequestedLineRow {
            item_id: r.get("item_id"),
            quantity: r.get("quantity"),
        }).collect())
    }
}

backbone_core::impl_crud_repository!(MaterialRequestItemRepository, MaterialRequestItem, soft_delete);
