//! Repository for MaterialRequest entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written MaterialRequest SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<MaterialRequest, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::org_scope;

use crate::domain::entity::MaterialRequest;

/// Table name for MaterialRequest entities
pub const TABLE_NAME: &str = "buying.material_requests";

/// Repository for MaterialRequest entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MaterialRequestRepository(
    backbone_orm::GenericCrudRepository<MaterialRequest, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for MaterialRequestRepository {
    type Target = backbone_orm::GenericCrudRepository<MaterialRequest, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MaterialRequestRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a material-request header insert writes.
///
/// Mirrors the raw column shape rather than the `MaterialRequest` entity: `request_type` binds as
/// `&str` and is cast at the DB (`$4::material_request_type`), so a bad value fails as a DB error
/// rather than a deserialize panic. `status` is not a field — the INSERT hard-codes `'draft'`.
pub struct NewMaterialRequestRow<'a> {
    pub id: Uuid,
    pub request_number: &'a str,
    pub request_type: &'a str,
    pub request_date: chrono::NaiveDate,
    pub schedule_date: Option<chrono::NaiveDate>,
    pub notes: Option<&'a str>,
}

/// A material request's convertibility state, as read by the MR→RFQ funnel step.
pub struct MaterialRequestSourceRow {
    pub status: String,
}

/// Hand-written MaterialRequest SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl MaterialRequestRepository {
    /// Insert a material-request header as `draft`.
    ///
    /// Takes the CALLER'S connection so the header and its lines commit as one unit. The caller has
    /// already relayed the ambient org scope onto it (`relay_ambient_scope`) — don't re-bind here.
    /// The module carries no tenancy of its own (ADR-0029): the composing service's decorator owns
    /// isolation.
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to
    /// turn a duplicate request number into a domain error.
    pub async fn insert_material_request(
        &self,
        conn: &mut sqlx::PgConnection,
        m: &NewMaterialRequestRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO buying.material_requests
                (id, request_number, request_type, status, request_date, schedule_date, notes)
               VALUES ($1,$2,$3::material_request_type,'draft'::purchase_doc_status,$4,$5,$6)"#,
        )
        .bind(m.id).bind(m.request_number).bind(m.request_type)
        .bind(m.request_date).bind(m.schedule_date).bind(m.notes)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read a material request's status for the MR→RFQ conversion. `Ok(None)` = not found.
    ///
    /// ID-only: no tenant argument. `fetch_optional_row_scoped` rides the request-dedicated
    /// connection when the composing service bound one (carrying the decorator's fence variables),
    /// plainly on the pool otherwise (ADR-0029).
    pub async fn fetch_source(
        &self,
        pool: &PgPool,
        request_id: Uuid,
    ) -> Result<Option<MaterialRequestSourceRow>, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT status::text AS st FROM buying.material_requests
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            ).bind(request_id),
        )
        .await?;
        Ok(row.map(|r| MaterialRequestSourceRow {
            status: r.get("st"),
        }))
    }

    /// Advance a material request to `ordered` once its RFQ is issued. Same caller-owned-tx contract
    /// as [`Self::insert_material_request`].
    pub async fn mark_ordered(
        &self,
        conn: &mut sqlx::PgConnection,
        request_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            "UPDATE buying.material_requests SET status='ordered'::purchase_doc_status WHERE id=$1",
        )
        .bind(request_id)
        .execute(conn)
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(MaterialRequestRepository, MaterialRequest, soft_delete);
