//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod material_request_repository;
mod material_request_item_repository;
mod purchase_order_repository;
mod purchase_order_item_repository;
mod request_for_quotation_repository;
mod rfq_item_repository;
mod rfq_supplier_repository;
mod supplier_quotation_repository;
mod supplier_quotation_item_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use material_request_repository::MaterialRequestRepository;
pub use material_request_item_repository::MaterialRequestItemRepository;
pub use purchase_order_repository::PurchaseOrderRepository;
pub use purchase_order_item_repository::PurchaseOrderItemRepository;
pub use request_for_quotation_repository::RequestForQuotationRepository;
pub use rfq_item_repository::RfqItemRepository;
pub use rfq_supplier_repository::RfqSupplierRepository;
pub use supplier_quotation_repository::SupplierQuotationRepository;
pub use supplier_quotation_item_repository::SupplierQuotationItemRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
