//! Repository for PurchaseAgreementLine entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written blanket-agreement line SQL (4-layer rule: services orchestrate,
//! repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PurchaseAgreementLine, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::PurchaseAgreementLine;

/// Table name for PurchaseAgreementLine entities
pub const TABLE_NAME: &str = "buying.purchase_agreement_lines";

/// Repository for PurchaseAgreementLine entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PurchaseAgreementLineRepository(
    backbone_orm::GenericCrudRepository<PurchaseAgreementLine, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PurchaseAgreementLineRepository {
    type Target = backbone_orm::GenericCrudRepository<PurchaseAgreementLine, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PurchaseAgreementLineRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a blanket-agreement line insert writes. `qty_ordered` starts at 0 — the call-off
/// verb is its only writer.
pub struct NewAgreementLineRow {
    pub id: Uuid,
    pub agreement_id: Uuid,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub rate: Decimal,
}

/// One agreement line, as the call-off path reads it: the blanket quantity, the negotiated rate,
/// and how much of the blanket has already been called off (`qty_ordered`).
pub struct AgreementLineRow {
    pub id: Uuid,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub rate: Decimal,
    pub qty_ordered: Decimal,
}

/// Hand-written PurchaseAgreementLine SQL. Lives here (not in the write service) per the module's
/// 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl PurchaseAgreementLineRepository {
    /// Insert one agreement line.
    ///
    /// Takes the CALLER'S connection so it commits with its header. The caller has already bound
    /// the company on it — don't re-bind here.
    pub async fn insert_line(
        &self,
        conn: &mut sqlx::PgConnection,
        l: &NewAgreementLineRow,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO buying.purchase_agreement_lines
                (id, agreement_id, company_id, item_id, quantity, rate, qty_ordered)
               VALUES ($1,$2,$3,$4,$5,$6,0)"#,
        )
        .bind(l.id).bind(l.agreement_id).bind(l.company_id).bind(l.item_id)
        .bind(l.quantity).bind(l.rate)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Soft-delete every live line of one agreement (the draft resequence's clearing step). Takes
    /// the caller's connection — it commits with the lines that replace them.
    pub async fn soft_delete_all_for_agreement(
        &self,
        conn: &mut sqlx::PgConnection,
        agreement_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"UPDATE buying.purchase_agreement_lines
                  SET metadata = jsonb_set(metadata, '{deleted_at}', to_jsonb(NOW()))
                WHERE agreement_id=$1 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(agreement_id)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read an agreement's live lines (the call-off price source). Pool-based, ID-only: rides the
    /// caller's RLS scope.
    pub async fn fetch_lines(
        &self,
        pool: &PgPool,
        agreement_id: Uuid,
    ) -> Result<Vec<AgreementLineRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, company_id, item_id, quantity, rate, qty_ordered
                   FROM buying.purchase_agreement_lines
                   WHERE agreement_id=$1 AND (metadata->>'deleted_at') IS NULL
                   ORDER BY id"#,
            ).bind(agreement_id),
        )
        .await?;
        Ok(rows.iter().map(|r| AgreementLineRow {
            id: r.get("id"),
            company_id: r.get("company_id"),
            item_id: r.get("item_id"),
            quantity: r.get("quantity"),
            rate: r.get("rate"),
            qty_ordered: r.get("qty_ordered"),
        }).collect())
    }

    /// Read one line (identity + parent + blanket quantities) for the price-update gate. Returns
    /// the line's agreement + supplier-side identity so the propagated supplier-price write can
    /// target the same row. `Ok(None)` = not found.
    pub async fn fetch_line(
        &self,
        pool: &PgPool,
        line_id: Uuid,
    ) -> Result<Option<AgreementLineRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, company_id, item_id, quantity, rate, qty_ordered
                   FROM buying.purchase_agreement_lines
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            ).bind(line_id),
        )
        .await?;
        Ok(row.map(|r| AgreementLineRow {
            id: r.get("id"),
            company_id: r.get("company_id"),
            item_id: r.get("item_id"),
            quantity: r.get("quantity"),
            rate: r.get("rate"),
            qty_ordered: r.get("qty_ordered"),
        }))
    }

    /// The agreement this line belongs to (status text), for the price-update gate (open only).
    pub async fn fetch_parent_status(
        &self,
        pool: &PgPool,
        line_id: Uuid,
    ) -> Result<Option<(Uuid, String)>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT l.agreement_id, a.status::text AS st
                   FROM buying.purchase_agreement_lines l
                   JOIN buying.purchase_agreements a ON a.id = l.agreement_id
                   WHERE l.id=$1 AND (l.metadata->>'deleted_at') IS NULL"#,
            ).bind(line_id),
        )
        .await?;
        Ok(row.map(|r| { let a: Uuid = r.get("agreement_id"); let s: String = r.get("st"); (a, s) }))
    }

    /// Set one line's negotiated rate (guarded by the service to agreements in `open`; the
    /// propagation to supplier_prices runs in the same transaction). Takes the caller's connection.
    pub async fn set_line_rate(
        &self,
        conn: &mut sqlx::PgConnection,
        line_id: Uuid,
        rate: Decimal,
    ) -> Result<(), sqlx::Error> {
        sqlx::query("UPDATE buying.purchase_agreement_lines SET rate=$2 WHERE id=$1")
            .bind(line_id).bind(rate)
            .execute(conn)
            .await?;
        Ok(())
    }

    /// Advance one line's `qty_ordered` by the called-off quantity. The service checks the
    /// blanket cap first; the `qty_ordered >= 0` CHECK is the DB floor. Takes the caller's
    /// connection so the call-off PO and its blanket consumption commit as one unit.
    pub async fn increment_qty_ordered(
        &self,
        conn: &mut sqlx::PgConnection,
        line_id: Uuid,
        qty: Decimal,
    ) -> Result<(), sqlx::Error> {
        sqlx::query("UPDATE buying.purchase_agreement_lines SET qty_ordered = qty_ordered + $2 WHERE id=$1")
            .bind(line_id).bind(qty)
            .execute(conn)
            .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(PurchaseAgreementLineRepository, PurchaseAgreementLine, soft_delete);
