//! Repository for PurchaseCompanySetting entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written settings SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PurchaseCompanySetting, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::org_scope;

use crate::domain::entity::PurchaseCompanySetting;

/// Table name for PurchaseCompanySetting entities
pub const TABLE_NAME: &str = "buying.purchase_company_settings";

/// Repository for PurchaseCompanySetting entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PurchaseCompanySettingRepository(
    backbone_orm::GenericCrudRepository<PurchaseCompanySetting, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PurchaseCompanySettingRepository {
    type Target = backbone_orm::GenericCrudRepository<PurchaseCompanySetting, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PurchaseCompanySettingRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The purchase settings, as the write paths read them. `Ok(None)` from
/// [`PurchaseCompanySettingRepository::fetch_settings`] = settings were never configured;
/// callers apply the schema defaults (one_step, 5000, IDR, reminders on) in that case.
pub struct CompanyPurchaseSettingsRow {
    pub double_validation: String,
    /// Denominated in the home currency — the double-validation gate converts the PO total INTO
    /// home currency (via the order-time `currency_rate` snapshot) before comparing.
    pub double_validation_amount: Decimal,
    pub company_currency: String,
    pub send_reminder: bool,
}

/// The fields a settings upsert may set. The row carries no tenant axis (ADR-0029) — the
/// composing service's tenancy decorator re-declares the one-live-row-per-scope unique
/// org-scoped.
pub struct SettingsUpsert<'a> {
    pub double_validation: &'a str,
    pub double_validation_amount: Decimal,
    pub company_currency: &'a str,
    pub send_reminder: bool,
}

/// Hand-written PurchaseCompanySetting SQL. Lives here (not in the write service) per the module's
/// 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl PurchaseCompanySettingRepository {
    /// Read the settings row. `Ok(None)` = not configured (defaults apply).
    ///
    /// The table is a plain settings table module-side (ADR-0029) — under a composed tenancy
    /// decorator the read rides the request-dedicated connection carrying the fence variables,
    /// so the row seen is the caller's own scope's; plainly on the pool otherwise.
    pub async fn fetch_settings(
        &self,
        pool: &PgPool,
    ) -> Result<Option<CompanyPurchaseSettingsRow>, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT double_validation::text AS dv, double_validation_amount,
                          company_currency, send_reminder
                   FROM buying.purchase_company_settings
                   WHERE (metadata->>'deleted_at') IS NULL"#,
            ),
        )
        .await?;
        Ok(row.map(|r| CompanyPurchaseSettingsRow {
            double_validation: r.get("dv"),
            double_validation_amount: r.get("double_validation_amount"),
            company_currency: r.get("company_currency"),
            send_reminder: r.get("send_reminder"),
        }))
    }

    /// Insert-or-update the one live settings row: the existing live row is updated when present,
    /// a fresh row inserted otherwise (no module-side unique backs the singleton — the composing
    /// service's tenancy decorator re-declares it org-scoped; ADR-0029).
    pub async fn upsert_settings(
        &self,
        pool: &PgPool,
        s: &SettingsUpsert<'_>,
    ) -> Result<(), sqlx::Error> {
        org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"WITH live AS (
                       SELECT id FROM buying.purchase_company_settings
                        WHERE (metadata->>'deleted_at') IS NULL
                        ORDER BY (metadata->>'created_at') ASC
                        LIMIT 1
                   ), upd AS (
                       UPDATE buying.purchase_company_settings st
                          SET double_validation = $2::double_validation,
                              double_validation_amount = $3,
                              company_currency = $4,
                              send_reminder = $5
                         FROM live WHERE st.id = live.id
                       RETURNING st.id
                   )
                   INSERT INTO buying.purchase_company_settings
                       (id, double_validation, double_validation_amount,
                        company_currency, send_reminder)
                   SELECT $1, $2::double_validation, $3, $4, $5
                    WHERE NOT EXISTS (SELECT 1 FROM upd)"#,
            )
            .bind(Uuid::new_v4())
            .bind(s.double_validation)
            .bind(s.double_validation_amount)
            .bind(s.company_currency)
            .bind(s.send_reminder),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(PurchaseCompanySettingRepository, PurchaseCompanySetting, soft_delete);
