//! Repository for PurchaseOrder entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written PurchaseOrder SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PurchaseOrder, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::PurchaseOrder;

/// Table name for PurchaseOrder entities
pub const TABLE_NAME: &str = "buying.purchase_orders";

/// Repository for PurchaseOrder entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PurchaseOrderRepository(
    backbone_orm::GenericCrudRepository<PurchaseOrder, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PurchaseOrderRepository {
    type Target = backbone_orm::GenericCrudRepository<PurchaseOrder, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PurchaseOrderRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a purchase-order header insert writes.
///
/// Mirrors the raw column shape rather than the `PurchaseOrder` entity: `order_kind` binds as `&str`
/// and is cast at the DB (`$4::order_kind`), so a bad value fails as a DB error rather than a
/// deserialize panic. `status` is not a field — the INSERT hard-codes `'draft'`. The money columns
/// carry the SERVER-computed totals (2dp half-up), not anything the caller sent.
pub struct NewPurchaseOrderRow<'a> {
    pub id: Uuid,
    pub po_number: &'a str,
    pub supplier_quotation_id: Option<Uuid>,
    pub order_kind: &'a str,
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub supplier_id: Uuid,
    pub order_date: chrono::NaiveDate,
    pub schedule_date: Option<chrono::NaiveDate>,
    pub currency: &'a str,
    pub subtotal: Decimal,
    pub tax_rate: Decimal,
    pub tax_amount: Decimal,
    pub total: Decimal,
    pub notes: Option<&'a str>,
}

/// A PO's cross-module reference projection (the brief §42 DTO's row shape).
pub struct PurchaseOrderRefRow {
    pub supplier_id: Uuid,
    pub company_id: Uuid,
    pub order_kind: String,
    pub total: Decimal,
    pub currency: String,
}

/// A PO's header, as read by the receipt seam.
pub struct PurchaseOrderHeaderRow {
    pub company_id: Uuid,
    pub supplier_id: Uuid,
    pub currency: String,
    pub status: String,
}

/// The PO fields returned by a successful confirmation.
pub struct ConfirmedOrderRow {
    pub company_id: Uuid,
    pub supplier_id: Uuid,
    pub total: Decimal,
    pub currency: String,
}

/// A PO's two 3-way-match watermarks aggregated across its lines, plus the status it held BEFORE the
/// recompute (the milestone events fire on the transition, so the prior value is load-bearing).
///
/// `received_all`/`billed_all` are `Option<bool>`: `bool_and` over zero rows yields NULL.
pub struct MatchWatermarkRow {
    pub company_id: Uuid,
    pub prior: String,
    pub received_all: Option<bool>,
    pub billed_all: Option<bool>,
}

/// Hand-written PurchaseOrder SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl PurchaseOrderRepository {
    /// Insert a purchase-order header as `draft`.
    ///
    /// Takes the CALLER'S connection so the header and its lines commit as one unit. The caller has
    /// already bound the company on it (`bind_company_on`) — don't re-bind here.
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to
    /// turn a duplicate PO number into a domain error.
    pub async fn insert_purchase_order(
        &self,
        conn: &mut sqlx::PgConnection,
        o: &NewPurchaseOrderRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO buying.purchase_orders
                (id, po_number, supplier_quotation_id, order_kind, company_id, branch_id, supplier_id,
                 status, order_date, schedule_date, currency, subtotal, tax_rate, tax_amount, total, notes)
               VALUES ($1,$2,$3,$4::order_kind,$5,$6,$7,'draft'::purchase_order_status,$8,$9,$10,$11,$12,$13,$14,$15)"#,
        )
        .bind(o.id).bind(o.po_number).bind(o.supplier_quotation_id).bind(o.order_kind).bind(o.company_id)
        .bind(o.branch_id).bind(o.supplier_id).bind(o.order_date).bind(o.schedule_date).bind(o.currency)
        .bind(o.subtotal).bind(o.tax_rate).bind(o.tax_amount).bind(o.total).bind(o.notes)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Load a PO's cross-module reference projection. `Ok(None)` = not found.
    ///
    /// ID-only: no company argument. `fetch_optional_row_scoped` means it rides a connection carrying
    /// the caller's `app.company_id`, so another company's PO simply is not found.
    pub async fn fetch_ref(
        &self,
        pool: &PgPool,
        order_id: Uuid,
    ) -> Result<Option<PurchaseOrderRefRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT supplier_id, company_id, order_kind::text AS kind, total, currency
                   FROM buying.purchase_orders WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            ).bind(order_id),
        )
        .await?;
        Ok(row.map(|r| PurchaseOrderRefRow {
            supplier_id: r.get("supplier_id"),
            company_id: r.get("company_id"),
            order_kind: r.get("kind"),
            total: r.get("total"),
            currency: r.get("currency"),
        }))
    }

    /// Read a PO's header for the receipt seam. `Ok(None)` = not found. ID-only + scoped read, as
    /// [`Self::fetch_ref`].
    pub async fn fetch_header(
        &self,
        pool: &PgPool,
        order_id: Uuid,
    ) -> Result<Option<PurchaseOrderHeaderRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, supplier_id, currency, status::text AS st
                   FROM buying.purchase_orders WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            ).bind(order_id),
        )
        .await?;
        Ok(row.map(|r| PurchaseOrderHeaderRow {
            company_id: r.get("company_id"),
            supplier_id: r.get("supplier_id"),
            currency: r.get("currency"),
            status: r.get("st"),
        }))
    }

    /// Confirm a `draft` PO → `to_receive_and_bill`, returning the fields the confirmation event
    /// carries. State-guarded on `draft`, so `Ok(None)` = absent or not confirmable.
    ///
    /// ID-only: the `UPDATE ... RETURNING` rides the request-dedicated connection carrying the
    /// caller's `app.company_id`, so it can only confirm a PO in the caller's own company.
    pub async fn confirm(
        &self,
        pool: &PgPool,
        order_id: Uuid,
    ) -> Result<Option<ConfirmedOrderRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"UPDATE buying.purchase_orders SET status='to_receive_and_bill'::purchase_order_status
                   WHERE id=$1 AND status='draft'::purchase_order_status AND (metadata->>'deleted_at') IS NULL
                   RETURNING company_id, supplier_id, total, currency"#,
            ).bind(order_id),
        )
        .await?;
        Ok(row.map(|r| ConfirmedOrderRow {
            company_id: r.get("company_id"),
            supplier_id: r.get("supplier_id"),
            total: r.get("total"),
            currency: r.get("currency"),
        }))
    }

    /// Aggregate a PO's 3-way-match watermarks across its lines, alongside its current (pre-recompute)
    /// status.
    ///
    /// ID-only: no company argument — this runs under whatever scope its caller established, i.e. the
    /// request connection under HTTP, or an event caller's `with_company_scope`.
    pub async fn fetch_match_watermarks(
        &self,
        pool: &PgPool,
        order_id: Uuid,
    ) -> Result<MatchWatermarkRow, sqlx::Error> {
        let row = company_scope::fetch_one_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT po.company_id, po.status::text AS prior,
                          bool_and(i.received_qty >= i.quantity) AS received_all,
                          bool_and(i.billed_qty >= i.quantity) AS billed_all
                   FROM buying.purchase_order_items i
                   JOIN buying.purchase_orders po ON po.id = i.order_id
                   WHERE i.order_id=$1 AND (i.metadata->>'deleted_at') IS NULL
                   GROUP BY po.company_id, po.status"#,
            ).bind(order_id),
        )
        .await?;
        Ok(MatchWatermarkRow {
            company_id: row.get("company_id"),
            prior: row.get("prior"),
            received_all: row.get("received_all"),
            billed_all: row.get("billed_all"),
        })
    }

    /// Flip a PO's status to the recomputed value. Guarded to the three in-flight statuses, so a
    /// `draft` or `cancelled` PO is never dragged forward by a stray watermark recompute.
    ///
    /// `status` binds as `&str` and is cast at the DB (`$2::purchase_order_status`). A write outside
    /// any transaction: the caller wraps this in `with_company_scope(Some(company))` using the company
    /// it just read off the PO's own row, so this is correct for non-request callers too.
    pub async fn update_status(
        &self,
        pool: &PgPool,
        order_id: Uuid,
        status: &str,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE buying.purchase_orders SET status=$2::purchase_order_status
                   WHERE id=$1 AND status = ANY(ARRAY['to_receive','to_bill','to_receive_and_bill']::purchase_order_status[])"#,
            ).bind(order_id).bind(status),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(PurchaseOrderRepository, PurchaseOrder, soft_delete);
