//! Repository for PurchaseCompanySetting entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written settings SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PurchaseCompanySetting, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::PurchaseCompanySetting;

/// Table name for PurchaseCompanySetting entities
pub const TABLE_NAME: &str = "buying.purchase_company_settings";

/// Repository for PurchaseCompanySetting entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PurchaseCompanySettingRepository(
    backbone_orm::GenericCrudRepository<PurchaseCompanySetting, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PurchaseCompanySettingRepository {
    type Target = backbone_orm::GenericCrudRepository<PurchaseCompanySetting, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PurchaseCompanySettingRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The company's purchase settings, as the write paths read them. `Ok(None)` from
/// [`PurchaseCompanySettingRepository::fetch_settings`] = the company never configured the row;
/// callers apply the schema defaults (one_step, 5000, IDR, reminders on) in that case.
pub struct CompanyPurchaseSettingsRow {
    pub double_validation: String,
    /// Denominated in the COMPANY currency — the double-validation gate converts the PO total INTO
    /// company currency (via the order-time `currency_rate` snapshot) before comparing.
    pub double_validation_amount: Decimal,
    pub company_currency: String,
    pub send_reminder: bool,
}

/// The fields a settings upsert may set. `company_id` rides the RLS scope, not the row.
pub struct SettingsUpsert<'a> {
    pub double_validation: &'a str,
    pub double_validation_amount: Decimal,
    pub company_currency: &'a str,
    pub send_reminder: bool,
}

/// Hand-written PurchaseCompanySetting SQL. Lives here (not in the write service) per the module's
/// 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl PurchaseCompanySettingRepository {
    /// Read the caller's company settings row. `Ok(None)` = not configured (defaults apply).
    ///
    /// ID-only: no company argument — the read rides the connection carrying the caller's
    /// `app.company_id` (request-dedicated under HTTP, or the scope a job/event caller established).
    pub async fn fetch_settings(
        &self,
        pool: &PgPool,
    ) -> Result<Option<CompanyPurchaseSettingsRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT double_validation::text AS dv, double_validation_amount,
                          company_currency, send_reminder
                   FROM buying.purchase_company_settings
                   WHERE (metadata->>'deleted_at') IS NULL"#,
            ),
        )
        .await?;
        Ok(row.map(|r| CompanyPurchaseSettingsRow {
            double_validation: r.get("dv"),
            double_validation_amount: r.get("double_validation_amount"),
            company_currency: r.get("company_currency"),
            send_reminder: r.get("send_reminder"),
        }))
    }

    /// Insert-or-update the caller's company settings row (one row per company). Company comes from
    /// the RLS scope the caller established — never from the row — so an upsert can only ever touch
    /// the caller's own company.
    pub async fn upsert_settings(
        &self,
        pool: &PgPool,
        s: &SettingsUpsert<'_>,
        company_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO buying.purchase_company_settings
                       (id, company_id, double_validation, double_validation_amount,
                        company_currency, send_reminder)
                   VALUES ($1,$2,$3::double_validation,$4,$5,$6)
                   ON CONFLICT (company_id) WHERE (metadata->>'deleted_at') IS NULL DO UPDATE SET
                       double_validation = EXCLUDED.double_validation,
                       double_validation_amount = EXCLUDED.double_validation_amount,
                       company_currency = EXCLUDED.company_currency,
                       send_reminder = EXCLUDED.send_reminder"#,
            )
            .bind(Uuid::new_v4())
            .bind(company_id)
            .bind(s.double_validation)
            .bind(s.double_validation_amount)
            .bind(s.company_currency)
            .bind(s.send_reminder),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(PurchaseCompanySettingRepository, PurchaseCompanySetting, soft_delete);
