//! Repository for RequestForQuotation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<RequestForQuotation, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::RequestForQuotation;

/// Table name for RequestForQuotation entities
pub const TABLE_NAME: &str = "buying.request_for_quotations";

/// Repository for RequestForQuotation entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct RequestForQuotationRepository(
    backbone_orm::GenericCrudRepository<RequestForQuotation, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for RequestForQuotationRepository {
    type Target = backbone_orm::GenericCrudRepository<RequestForQuotation, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl RequestForQuotationRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(RequestForQuotationRepository, RequestForQuotation, soft_delete);
