//! Repository for RfqSupplier entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<RfqSupplier, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::RfqSupplier;

/// Table name for RfqSupplier entities
pub const TABLE_NAME: &str = "buying.rfq_suppliers";

/// Repository for RfqSupplier entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct RfqSupplierRepository(
    backbone_orm::GenericCrudRepository<RfqSupplier, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for RfqSupplierRepository {
    type Target = backbone_orm::GenericCrudRepository<RfqSupplier, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl RfqSupplierRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(RfqSupplierRepository, RfqSupplier, soft_delete);
