//! Repository for RfqSupplier entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written RfqSupplier SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<RfqSupplier, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::RfqSupplier;

/// Table name for RfqSupplier entities
pub const TABLE_NAME: &str = "buying.rfq_suppliers";

/// Repository for RfqSupplier entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct RfqSupplierRepository(
    backbone_orm::GenericCrudRepository<RfqSupplier, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for RfqSupplierRepository {
    type Target = backbone_orm::GenericCrudRepository<RfqSupplier, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl RfqSupplierRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an RFQ supplier-invitation insert writes.
pub struct NewRfqSupplierRow {
    pub id: Uuid,
    pub rfq_id: Uuid,
    pub supplier_id: Uuid,
}

/// Hand-written RfqSupplier SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl RfqSupplierRepository {
    /// Invite one supplier onto an RFQ.
    ///
    /// Takes the CALLER'S connection so it commits with its header. The caller has already bound the
    /// company on it (`bind_company_on`) — don't re-bind here.
    pub async fn insert_supplier(
        &self,
        conn: &mut sqlx::PgConnection,
        s: &NewRfqSupplierRow,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            "INSERT INTO buying.rfq_suppliers (id, rfq_id, supplier_id) VALUES ($1,$2,$3)",
        )
        .bind(s.id).bind(s.rfq_id).bind(s.supplier_id)
        .execute(conn)
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(RfqSupplierRepository, RfqSupplier, soft_delete);
