//! Repository for SupplierReminderSetting entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written supplier-reminder SQL (4-layer rule: services orchestrate, repos
//! hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SupplierReminderSetting, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::SupplierReminderSetting;

/// Table name for SupplierReminderSetting entities
pub const TABLE_NAME: &str = "buying.supplier_reminder_settings";

/// Repository for SupplierReminderSetting entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SupplierReminderSettingRepository(
    backbone_orm::GenericCrudRepository<SupplierReminderSetting, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SupplierReminderSettingRepository {
    type Target = backbone_orm::GenericCrudRepository<SupplierReminderSetting, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SupplierReminderSettingRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The supplier-level reminder overrides, as the reminder job reads them.
pub struct SupplierReminderRow {
    pub supplier_id: Uuid,
    pub receipt_reminder_email: bool,
    pub reminder_days_before: i32,
}

/// The fields a supplier-reminder upsert may set. `company_id` rides the RLS scope.
pub struct SupplierReminderUpsert {
    pub supplier_id: Uuid,
    pub receipt_reminder_email: bool,
    pub reminder_days_before: i32,
}

/// Hand-written SupplierReminderSetting SQL. Lives here (not in the write service) per the module's
/// 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl SupplierReminderSettingRepository {
    /// Read one supplier's reminder settings. `Ok(None)` = not configured → the job's enabled
    /// defaults (remind, 1 day before) apply; the COMPANY-level `send_reminder=false` is the only
    /// off-switch (G7).
    ///
    /// ID-only: the read rides the connection carrying the caller's `app.company_id`.
    pub async fn fetch_for_supplier(
        &self,
        pool: &PgPool,
        supplier_id: Uuid,
    ) -> Result<Option<SupplierReminderRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT supplier_id, receipt_reminder_email, reminder_days_before
                   FROM buying.supplier_reminder_settings
                   WHERE supplier_id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            ).bind(supplier_id),
        )
        .await?;
        Ok(row.map(|r| SupplierReminderRow {
            supplier_id: r.get("supplier_id"),
            receipt_reminder_email: r.get("receipt_reminder_email"),
            reminder_days_before: r.get("reminder_days_before"),
        }))
    }

    /// Insert-or-update one supplier's reminder settings (one row per company+supplier). Company
    /// comes from the RLS scope the caller established — never from the row.
    pub async fn upsert_for_supplier(
        &self,
        pool: &PgPool,
        s: &SupplierReminderUpsert,
        company_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO buying.supplier_reminder_settings
                       (id, company_id, supplier_id, receipt_reminder_email, reminder_days_before)
                   VALUES ($1,$2,$3,$4,$5)
                   ON CONFLICT (company_id, supplier_id) WHERE (metadata->>'deleted_at') IS NULL DO UPDATE SET
                       receipt_reminder_email = EXCLUDED.receipt_reminder_email,
                       reminder_days_before = EXCLUDED.reminder_days_before"#,
            )
            .bind(Uuid::new_v4())
            .bind(company_id)
            .bind(s.supplier_id)
            .bind(s.receipt_reminder_email)
            .bind(s.reminder_days_before),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(SupplierReminderSettingRepository, SupplierReminderSetting, soft_delete);
