//! Repository for SupplierQuotation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SupplierQuotation, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::SupplierQuotation;

/// Table name for SupplierQuotation entities
pub const TABLE_NAME: &str = "buying.supplier_quotations";

/// Repository for SupplierQuotation entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SupplierQuotationRepository(
    backbone_orm::GenericCrudRepository<SupplierQuotation, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SupplierQuotationRepository {
    type Target = backbone_orm::GenericCrudRepository<SupplierQuotation, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SupplierQuotationRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SupplierQuotationRepository, SupplierQuotation, soft_delete);
