//! Repository for SupplierReminderSetting entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written supplier-reminder SQL (4-layer rule: services orchestrate, repos
//! hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SupplierReminderSetting, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::org_scope;

use crate::domain::entity::SupplierReminderSetting;

/// Table name for SupplierReminderSetting entities
pub const TABLE_NAME: &str = "buying.supplier_reminder_settings";

/// Repository for SupplierReminderSetting entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SupplierReminderSettingRepository(
    backbone_orm::GenericCrudRepository<SupplierReminderSetting, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SupplierReminderSettingRepository {
    type Target = backbone_orm::GenericCrudRepository<SupplierReminderSetting, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SupplierReminderSettingRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The supplier-level reminder overrides, as the reminder job reads them.
pub struct SupplierReminderRow {
    pub supplier_id: Uuid,
    pub receipt_reminder_email: bool,
    pub reminder_days_before: i32,
}

/// The fields a supplier-reminder upsert may set. The row carries no tenant axis (ADR-0029) —
/// the composing service's tenancy decorator re-declares the one-row-per-supplier unique
/// org-scoped.
pub struct SupplierReminderUpsert {
    pub supplier_id: Uuid,
    pub receipt_reminder_email: bool,
    pub reminder_days_before: i32,
}

/// Hand-written SupplierReminderSetting SQL. Lives here (not in the write service) per the module's
/// 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl SupplierReminderSettingRepository {
    /// Read one supplier's reminder settings. `Ok(None)` = not configured → the job's enabled
    /// defaults (remind, 1 day before) apply; the settings-level `send_reminder=false` is the only
    /// off-switch (G7).
    ///
    /// Rides the request-dedicated connection when the composing service bound one (carrying the
    /// decorator's fence variables), plainly on the pool otherwise (ADR-0029).
    pub async fn fetch_for_supplier(
        &self,
        pool: &PgPool,
        supplier_id: Uuid,
    ) -> Result<Option<SupplierReminderRow>, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT supplier_id, receipt_reminder_email, reminder_days_before
                   FROM buying.supplier_reminder_settings
                   WHERE supplier_id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            ).bind(supplier_id),
        )
        .await?;
        Ok(row.map(|r| SupplierReminderRow {
            supplier_id: r.get("supplier_id"),
            receipt_reminder_email: r.get("receipt_reminder_email"),
            reminder_days_before: r.get("reminder_days_before"),
        }))
    }

    /// Insert-or-update one supplier's reminder settings: the supplier's live row is updated when
    /// present, a fresh row inserted otherwise (no module-side unique backs the one-row-per-
    /// supplier shape — the composing service's tenancy decorator re-declares it org-scoped;
    /// ADR-0029).
    pub async fn upsert_for_supplier(
        &self,
        pool: &PgPool,
        s: &SupplierReminderUpsert,
    ) -> Result<(), sqlx::Error> {
        org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"WITH live AS (
                       SELECT id FROM buying.supplier_reminder_settings
                        WHERE supplier_id = $2
                          AND (metadata->>'deleted_at') IS NULL
                        ORDER BY (metadata->>'created_at') ASC
                        LIMIT 1
                   ), upd AS (
                       UPDATE buying.supplier_reminder_settings st
                          SET receipt_reminder_email = $3,
                              reminder_days_before = $4
                         FROM live WHERE st.id = live.id
                       RETURNING st.id
                   )
                   INSERT INTO buying.supplier_reminder_settings
                       (id, supplier_id, receipt_reminder_email, reminder_days_before)
                   SELECT $1, $2, $3, $4
                    WHERE NOT EXISTS (SELECT 1 FROM upd)"#,
            )
            .bind(Uuid::new_v4())
            .bind(s.supplier_id)
            .bind(s.receipt_reminder_email)
            .bind(s.reminder_days_before),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(SupplierReminderSettingRepository, SupplierReminderSetting, soft_delete);
