//! Repository for SupplierQuotation entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written SupplierQuotation SQL (4-layer rule: services orchestrate, repos hold
//! SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SupplierQuotation, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::SupplierQuotation;

/// Table name for SupplierQuotation entities
pub const TABLE_NAME: &str = "buying.supplier_quotations";

/// Repository for SupplierQuotation entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SupplierQuotationRepository(
    backbone_orm::GenericCrudRepository<SupplierQuotation, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SupplierQuotationRepository {
    type Target = backbone_orm::GenericCrudRepository<SupplierQuotation, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SupplierQuotationRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a supplier-quotation header insert writes.
///
/// `status` is not a field — the INSERT hard-codes `'submitted'`.
pub struct NewSupplierQuotationRow<'a> {
    pub id: Uuid,
    pub quotation_number: &'a str,
    pub rfq_id: Option<Uuid>,
    pub company_id: Uuid,
    pub supplier_id: Uuid,
    pub quotation_date: chrono::NaiveDate,
    pub valid_till: Option<chrono::NaiveDate>,
    pub currency: &'a str,
}

/// The exact row an RFQ→SupplierQuotation conversion writes.
///
/// Deliberately NOT the same shape as [`NewSupplierQuotationRow`]: the conversion hard-codes
/// `CURRENT_DATE` and `'IDR'` and carries no `valid_till`, so those are not fields here.
pub struct NewQuotationFromRfqRow<'a> {
    pub id: Uuid,
    pub quotation_number: &'a str,
    pub rfq_id: Uuid,
    pub company_id: Uuid,
    pub supplier_id: Uuid,
}

/// A supplier quotation's convertibility state + the header fields the SQ→PO step copies forward.
pub struct SupplierQuotationSourceRow {
    pub company_id: Uuid,
    pub supplier_id: Uuid,
    pub currency: String,
    pub status: String,
}

/// Hand-written SupplierQuotation SQL. Lives here (not in the write service) per the module's
/// 4-layer rule.
impl SupplierQuotationRepository {
    /// Insert a supplier-quotation header as `submitted`.
    ///
    /// Takes the CALLER'S connection so the header and its lines commit as one unit. The caller has
    /// already bound the company on it (`bind_company_on`) — don't re-bind here.
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to
    /// turn a duplicate quotation number into a domain error.
    pub async fn insert_quotation(
        &self,
        conn: &mut sqlx::PgConnection,
        q: &NewSupplierQuotationRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO buying.supplier_quotations
                (id, quotation_number, rfq_id, company_id, supplier_id, status, quotation_date, valid_till, currency)
               VALUES ($1,$2,$3,$4,$5,'submitted'::purchase_doc_status,$6,$7,$8)"#,
        )
        .bind(q.id).bind(q.quotation_number).bind(q.rfq_id).bind(q.company_id).bind(q.supplier_id)
        .bind(q.quotation_date).bind(q.valid_till).bind(q.currency)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Insert a supplier-quotation header converted from an RFQ — dated today, in IDR. Same
    /// caller-owned-tx and unique-violation contract as [`Self::insert_quotation`].
    pub async fn insert_quotation_from_rfq(
        &self,
        conn: &mut sqlx::PgConnection,
        q: &NewQuotationFromRfqRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO buying.supplier_quotations
                (id, quotation_number, rfq_id, company_id, supplier_id, status, quotation_date, currency)
               VALUES ($1,$2,$3,$4,$5,'submitted'::purchase_doc_status,CURRENT_DATE,'IDR')"#,
        )
        .bind(q.id).bind(q.quotation_number).bind(q.rfq_id).bind(q.company_id).bind(q.supplier_id)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read a supplier quotation's header for the SQ→PO conversion. `Ok(None)` = not found. ID-only +
    /// scoped read — see [`super::MaterialRequestRepository::fetch_source`].
    pub async fn fetch_source(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
    ) -> Result<Option<SupplierQuotationSourceRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, supplier_id, currency, status::text AS st
                   FROM buying.supplier_quotations WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            ).bind(quotation_id),
        )
        .await?;
        Ok(row.map(|r| SupplierQuotationSourceRow {
            company_id: r.get("company_id"),
            supplier_id: r.get("supplier_id"),
            currency: r.get("currency"),
            status: r.get("st"),
        }))
    }

    /// Advance a supplier quotation to `ordered` once its PO is raised.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` using the
    /// company it just read off the SQ's own row — so this is correct for non-request callers too.
    pub async fn mark_ordered(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                "UPDATE buying.supplier_quotations SET status='ordered'::purchase_doc_status WHERE id=$1",
            ).bind(quotation_id),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(SupplierQuotationRepository, SupplierQuotation, soft_delete);
