//! Validator for PurchaseCompanySetting entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PurchaseCompanySetting>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::PurchaseCompanySetting;

/// Validator type alias for PurchaseCompanySetting entities.
pub type PurchaseCompanySettingValidator = EntityValidator<PurchaseCompanySetting>;

/// Build a validator for PurchaseCompanySetting with all schema-defined field rules.
pub fn purchase_company_setting_validator() -> PurchaseCompanySettingValidator {
    EntityValidator::new()
        .rule(RequiredString::new("company_currency", |e: &PurchaseCompanySetting| &e.company_currency))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
