//! Validator for PurchaseAgreementLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PurchaseAgreementLine>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::PurchaseAgreementLine;

/// Validator type alias for PurchaseAgreementLine entities.
pub type PurchaseAgreementLineValidator = EntityValidator<PurchaseAgreementLine>;

/// Build a validator for PurchaseAgreementLine with all schema-defined field rules.
pub fn purchase_agreement_line_validator() -> PurchaseAgreementLineValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
