//! Validator for SupplierPrice entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SupplierPrice>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::SupplierPrice;

/// Validator type alias for SupplierPrice entities.
pub type SupplierPriceValidator = EntityValidator<SupplierPrice>;

/// Build a validator for SupplierPrice with all schema-defined field rules.
pub fn supplier_price_validator() -> SupplierPriceValidator {
    EntityValidator::new()
        .rule(RequiredString::new("currency", |e: &SupplierPrice| &e.currency))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
