//! Validator for SupplierQuotation entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SupplierQuotation>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::SupplierQuotation;

/// Validator type alias for SupplierQuotation entities.
pub type SupplierQuotationValidator = EntityValidator<SupplierQuotation>;

/// Build a validator for SupplierQuotation with all schema-defined field rules.
pub fn supplier_quotation_validator() -> SupplierQuotationValidator {
    EntityValidator::new()
        .rule(RequiredString::new("quotation_number", |e: &SupplierQuotation| &e.quotation_number))
        .rule(RequiredString::new("currency", |e: &SupplierQuotation| &e.currency))
        .rule(OptionalNotBlank::new("notes", |e: &SupplierQuotation| e.notes.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
