//! Auth configuration for MaterialRequestItem handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<MaterialRequestItem>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::MaterialRequestItemService;
use crate::domain::entity::MaterialRequestItem;

/// Permission string constants for MaterialRequestItem operations.
pub mod permissions {
    pub const LIST:        &str = "material_request_item:list";
    pub const READ:        &str = "material_request_item:read";
    pub const CREATE:      &str = "material_request_item:create";
    pub const UPDATE:      &str = "material_request_item:update";
    pub const DELETE:      &str = "material_request_item:delete";
    pub const RESTORE:     &str = "material_request_item:restore";
    pub const TRASH:       &str = "material_request_item:trash";
    pub const EMPTY_TRASH: &str = "material_request_item:empty_trash";
    pub const BULK_CREATE: &str = "material_request_item:bulk_create";
    pub const UPSERT:      &str = "material_request_item:upsert";
}

/// Resource policy for MaterialRequestItem — maps CRUD actions to permission strings.
pub struct MaterialRequestItemPolicy;

#[async_trait]
impl ResourcePolicy<MaterialRequestItem> for MaterialRequestItemPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &MaterialRequestItem,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for MaterialRequestItem handlers.
///
/// Wraps `MaterialRequestItemService` and checks `MaterialRequestItemPolicy` before delegating.
pub type MaterialRequestItemGuard = PermissionGuard<MaterialRequestItem>;

/// Service-integrated permission guard for MaterialRequestItem (for use in generated handlers).
pub type MaterialRequestItemServiceGuard = ServicePermissionGuard<MaterialRequestItem, MaterialRequestItemService, MaterialRequestItemPolicy>;

// <<< CUSTOM
// END CUSTOM
