//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod material_request_auth;
pub mod material_request_item_auth;
pub mod purchase_order_auth;
pub mod purchase_order_item_auth;
pub mod request_for_quotation_auth;
pub mod rfq_item_auth;
pub mod rfq_supplier_auth;
pub mod supplier_quotation_auth;
pub mod supplier_quotation_item_auth;

pub use material_request_auth::{MaterialRequestPolicy, MaterialRequestGuard, MaterialRequestServiceGuard};
pub use material_request_item_auth::{MaterialRequestItemPolicy, MaterialRequestItemGuard, MaterialRequestItemServiceGuard};
pub use purchase_order_auth::{PurchaseOrderPolicy, PurchaseOrderGuard, PurchaseOrderServiceGuard};
pub use purchase_order_item_auth::{PurchaseOrderItemPolicy, PurchaseOrderItemGuard, PurchaseOrderItemServiceGuard};
pub use request_for_quotation_auth::{RequestForQuotationPolicy, RequestForQuotationGuard, RequestForQuotationServiceGuard};
pub use rfq_item_auth::{RfqItemPolicy, RfqItemGuard, RfqItemServiceGuard};
pub use rfq_supplier_auth::{RfqSupplierPolicy, RfqSupplierGuard, RfqSupplierServiceGuard};
pub use supplier_quotation_auth::{SupplierQuotationPolicy, SupplierQuotationGuard, SupplierQuotationServiceGuard};
pub use supplier_quotation_item_auth::{SupplierQuotationItemPolicy, SupplierQuotationItemGuard, SupplierQuotationItemServiceGuard};

// <<< CUSTOM
// END CUSTOM
