//! Auth configuration for RequestForQuotation handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<RequestForQuotation>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::RequestForQuotationService;
use crate::domain::entity::RequestForQuotation;

/// Permission string constants for RequestForQuotation operations.
pub mod permissions {
    pub const LIST:        &str = "request_for_quotation:list";
    pub const READ:        &str = "request_for_quotation:read";
    pub const CREATE:      &str = "request_for_quotation:create";
    pub const UPDATE:      &str = "request_for_quotation:update";
    pub const DELETE:      &str = "request_for_quotation:delete";
    pub const RESTORE:     &str = "request_for_quotation:restore";
    pub const TRASH:       &str = "request_for_quotation:trash";
    pub const EMPTY_TRASH: &str = "request_for_quotation:empty_trash";
    pub const BULK_CREATE: &str = "request_for_quotation:bulk_create";
    pub const UPSERT:      &str = "request_for_quotation:upsert";
}

/// Resource policy for RequestForQuotation — maps CRUD actions to permission strings.
pub struct RequestForQuotationPolicy;

#[async_trait]
impl ResourcePolicy<RequestForQuotation> for RequestForQuotationPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &RequestForQuotation,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for RequestForQuotation handlers.
///
/// Wraps `RequestForQuotationService` and checks `RequestForQuotationPolicy` before delegating.
pub type RequestForQuotationGuard = PermissionGuard<RequestForQuotation>;

/// Service-integrated permission guard for RequestForQuotation (for use in generated handlers).
pub type RequestForQuotationServiceGuard = ServicePermissionGuard<RequestForQuotation, RequestForQuotationService, RequestForQuotationPolicy>;

// <<< CUSTOM
// END CUSTOM
