//! Auth configuration for RfqSupplier handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<RfqSupplier>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::RfqSupplierService;
use crate::domain::entity::RfqSupplier;

/// Permission string constants for RfqSupplier operations.
pub mod permissions {
    pub const LIST:        &str = "rfq_supplier:list";
    pub const READ:        &str = "rfq_supplier:read";
    pub const CREATE:      &str = "rfq_supplier:create";
    pub const UPDATE:      &str = "rfq_supplier:update";
    pub const DELETE:      &str = "rfq_supplier:delete";
    pub const RESTORE:     &str = "rfq_supplier:restore";
    pub const TRASH:       &str = "rfq_supplier:trash";
    pub const EMPTY_TRASH: &str = "rfq_supplier:empty_trash";
    pub const BULK_CREATE: &str = "rfq_supplier:bulk_create";
    pub const UPSERT:      &str = "rfq_supplier:upsert";
}

/// Resource policy for RfqSupplier — maps CRUD actions to permission strings.
pub struct RfqSupplierPolicy;

#[async_trait]
impl ResourcePolicy<RfqSupplier> for RfqSupplierPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &RfqSupplier,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for RfqSupplier handlers.
///
/// Wraps `RfqSupplierService` and checks `RfqSupplierPolicy` before delegating.
pub type RfqSupplierGuard = PermissionGuard<RfqSupplier>;

/// Service-integrated permission guard for RfqSupplier (for use in generated handlers).
pub type RfqSupplierServiceGuard = ServicePermissionGuard<RfqSupplier, RfqSupplierService, RfqSupplierPolicy>;

// <<< CUSTOM
// END CUSTOM
