//! Auth configuration for SupplierQuotationItem handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<SupplierQuotationItem>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SupplierQuotationItemService;
use crate::domain::entity::SupplierQuotationItem;

/// Permission string constants for SupplierQuotationItem operations.
pub mod permissions {
    pub const LIST:        &str = "supplier_quotation_item:list";
    pub const READ:        &str = "supplier_quotation_item:read";
    pub const CREATE:      &str = "supplier_quotation_item:create";
    pub const UPDATE:      &str = "supplier_quotation_item:update";
    pub const DELETE:      &str = "supplier_quotation_item:delete";
    pub const RESTORE:     &str = "supplier_quotation_item:restore";
    pub const TRASH:       &str = "supplier_quotation_item:trash";
    pub const EMPTY_TRASH: &str = "supplier_quotation_item:empty_trash";
    pub const BULK_CREATE: &str = "supplier_quotation_item:bulk_create";
    pub const UPSERT:      &str = "supplier_quotation_item:upsert";
}

/// Resource policy for SupplierQuotationItem — maps CRUD actions to permission strings.
pub struct SupplierQuotationItemPolicy;

#[async_trait]
impl ResourcePolicy<SupplierQuotationItem> for SupplierQuotationItemPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &SupplierQuotationItem,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for SupplierQuotationItem handlers.
///
/// Wraps `SupplierQuotationItemService` and checks `SupplierQuotationItemPolicy` before delegating.
pub type SupplierQuotationItemGuard = PermissionGuard<SupplierQuotationItem>;

/// Service-integrated permission guard for SupplierQuotationItem (for use in generated handlers).
pub type SupplierQuotationItemServiceGuard = ServicePermissionGuard<SupplierQuotationItem, SupplierQuotationItemService, SupplierQuotationItemPolicy>;

// <<< CUSTOM
// END CUSTOM
