//! Auth configuration for SupplierQuotation handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<SupplierQuotation>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SupplierQuotationService;
use crate::domain::entity::SupplierQuotation;

/// Permission string constants for SupplierQuotation operations.
pub mod permissions {
    pub const LIST:        &str = "supplier_quotation:list";
    pub const READ:        &str = "supplier_quotation:read";
    pub const CREATE:      &str = "supplier_quotation:create";
    pub const UPDATE:      &str = "supplier_quotation:update";
    pub const DELETE:      &str = "supplier_quotation:delete";
    pub const RESTORE:     &str = "supplier_quotation:restore";
    pub const TRASH:       &str = "supplier_quotation:trash";
    pub const EMPTY_TRASH: &str = "supplier_quotation:empty_trash";
    pub const BULK_CREATE: &str = "supplier_quotation:bulk_create";
    pub const UPSERT:      &str = "supplier_quotation:upsert";
}

/// Resource policy for SupplierQuotation — maps CRUD actions to permission strings.
pub struct SupplierQuotationPolicy;

#[async_trait]
impl ResourcePolicy<SupplierQuotation> for SupplierQuotationPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &SupplierQuotation,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for SupplierQuotation handlers.
///
/// Wraps `SupplierQuotationService` and checks `SupplierQuotationPolicy` before delegating.
pub type SupplierQuotationGuard = PermissionGuard<SupplierQuotation>;

/// Service-integrated permission guard for SupplierQuotation (for use in generated handlers).
pub type SupplierQuotationServiceGuard = ServicePermissionGuard<SupplierQuotation, SupplierQuotationService, SupplierQuotationPolicy>;

// <<< CUSTOM
// END CUSTOM
