//! MaterialRequest API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the MaterialRequest CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// MATERIALREQUEST TEST DATA GENERATOR
// ============================================================================

/// Test data generator for MaterialRequest
pub struct MaterialRequestTestData;

impl TestDataGenerator for MaterialRequestTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "request_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "company_id": Uuid::new_v4().to_string(),
            "request_type": "purchase",
            "status": "draft",
            "request_date": Utc::now().format("%Y-%m-%d").to_string(),
            "schedule_date": null,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "request_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "company_id": Uuid::new_v4().to_string(),
            "request_type": "purchase",
            "status": "draft",
            "request_date": Utc::now().format("%Y-%m-%d").to_string(),
            "schedule_date": null,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// MATERIALREQUEST API TEST
// ============================================================================

/// MaterialRequest API test suite
pub struct MaterialRequestApiTest {
    inner: GenericCrudTest<MaterialRequestTestData>,
}

impl MaterialRequestApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/material_requests", "MaterialRequest");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, MaterialRequestTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for MaterialRequestApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_material_request_crud() {
        let mut test = MaterialRequestApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add MaterialRequest specific tests here
// <<< CUSTOM TESTS END >>>
