//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod material_request_api_test;
pub mod material_request_item_api_test;
pub mod purchase_order_api_test;
pub mod purchase_order_item_api_test;
pub mod request_for_quotation_api_test;
pub mod rfq_item_api_test;
pub mod rfq_supplier_api_test;
pub mod supplier_quotation_api_test;
pub mod supplier_quotation_item_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use material_request_api_test::*;
pub use material_request_item_api_test::*;
pub use purchase_order_api_test::*;
pub use purchase_order_item_api_test::*;
pub use request_for_quotation_api_test::*;
pub use rfq_item_api_test::*;
pub use rfq_supplier_api_test::*;
pub use supplier_quotation_api_test::*;
pub use supplier_quotation_item_api_test::*;
