//! PurchaseAgreement API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PurchaseAgreement CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PURCHASEAGREEMENT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PurchaseAgreement
pub struct PurchaseAgreementTestData;

impl TestDataGenerator for PurchaseAgreementTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "agreement_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "agreement_kind": "blanket",
            "status": "draft",
            "company_id": Uuid::new_v4().to_string(),
            "supplier_id": Uuid::new_v4().to_string(),
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "date_start": null,
            "date_end": null,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "agreement_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "agreement_kind": "blanket",
            "status": "draft",
            "company_id": Uuid::new_v4().to_string(),
            "supplier_id": Uuid::new_v4().to_string(),
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "date_start": null,
            "date_end": null,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// PURCHASEAGREEMENT API TEST
// ============================================================================

/// PurchaseAgreement API test suite
pub struct PurchaseAgreementApiTest {
    inner: GenericCrudTest<PurchaseAgreementTestData>,
}

impl PurchaseAgreementApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/purchase_agreements", "PurchaseAgreement");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PurchaseAgreementTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PurchaseAgreementApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_purchase_agreement_crud() {
        let mut test = PurchaseAgreementApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PurchaseAgreement specific tests here
// <<< CUSTOM TESTS END >>>
