//! RequestForQuotation API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the RequestForQuotation CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// REQUESTFORQUOTATION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for RequestForQuotation
pub struct RequestForQuotationTestData;

impl TestDataGenerator for RequestForQuotationTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "rfq_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "material_request_id": null,
            "company_id": Uuid::new_v4().to_string(),
            "status": "draft",
            "rfq_date": Utc::now().format("%Y-%m-%d").to_string(),
            "response_due": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "rfq_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "material_request_id": null,
            "company_id": Uuid::new_v4().to_string(),
            "status": "draft",
            "rfq_date": Utc::now().format("%Y-%m-%d").to_string(),
            "response_due": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// REQUESTFORQUOTATION API TEST
// ============================================================================

/// RequestForQuotation API test suite
pub struct RequestForQuotationApiTest {
    inner: GenericCrudTest<RequestForQuotationTestData>,
}

impl RequestForQuotationApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/request_for_quotations", "RequestForQuotation");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, RequestForQuotationTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for RequestForQuotationApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_request_for_quotation_crud() {
        let mut test = RequestForQuotationApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add RequestForQuotation specific tests here
// <<< CUSTOM TESTS END >>>
