//! Buying Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::MaterialRequestService;
use crate::application::service::MaterialRequestItemService;
use crate::application::service::PurchaseOrderService;
use crate::application::service::PurchaseOrderItemService;
use crate::application::service::RequestForQuotationService;
use crate::application::service::RfqItemService;
use crate::application::service::RfqSupplierService;
use crate::application::service::SupplierQuotationService;
use crate::application::service::SupplierQuotationItemService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// MaterialRequest service
    pub material_request_service: Arc<MaterialRequestService>,
    /// MaterialRequestItem service
    pub material_request_item_service: Arc<MaterialRequestItemService>,
    /// PurchaseOrder service
    pub purchase_order_service: Arc<PurchaseOrderService>,
    /// PurchaseOrderItem service
    pub purchase_order_item_service: Arc<PurchaseOrderItemService>,
    /// RequestForQuotation service
    pub request_for_quotation_service: Arc<RequestForQuotationService>,
    /// RfqItem service
    pub rfq_item_service: Arc<RfqItemService>,
    /// RfqSupplier service
    pub rfq_supplier_service: Arc<RfqSupplierService>,
    /// SupplierQuotation service
    pub supplier_quotation_service: Arc<SupplierQuotationService>,
    /// SupplierQuotationItem service
    pub supplier_quotation_item_service: Arc<SupplierQuotationItemService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        material_request_service: Arc<MaterialRequestService>,
        material_request_item_service: Arc<MaterialRequestItemService>,
        purchase_order_service: Arc<PurchaseOrderService>,
        purchase_order_item_service: Arc<PurchaseOrderItemService>,
        request_for_quotation_service: Arc<RequestForQuotationService>,
        rfq_item_service: Arc<RfqItemService>,
        rfq_supplier_service: Arc<RfqSupplierService>,
        supplier_quotation_service: Arc<SupplierQuotationService>,
        supplier_quotation_item_service: Arc<SupplierQuotationItemService>
    ) -> Self {
        Self {
            material_request_service,
            material_request_item_service,
            purchase_order_service,
            purchase_order_item_service,
            request_for_quotation_service,
            rfq_item_service,
            rfq_supplier_service,
            supplier_quotation_service,
            supplier_quotation_item_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::BuyingModule) -> Self {
        Self {
            material_request_service: module.material_request_service.clone(),
            material_request_item_service: module.material_request_item_service.clone(),
            purchase_order_service: module.purchase_order_service.clone(),
            purchase_order_item_service: module.purchase_order_item_service.clone(),
            request_for_quotation_service: module.request_for_quotation_service.clone(),
            rfq_item_service: module.rfq_item_service.clone(),
            rfq_supplier_service: module.rfq_supplier_service.clone(),
            supplier_quotation_service: module.supplier_quotation_service.clone(),
            supplier_quotation_item_service: module.supplier_quotation_item_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    material_request_service: Option<Arc<MaterialRequestService>>,
    material_request_item_service: Option<Arc<MaterialRequestItemService>>,
    purchase_order_service: Option<Arc<PurchaseOrderService>>,
    purchase_order_item_service: Option<Arc<PurchaseOrderItemService>>,
    request_for_quotation_service: Option<Arc<RequestForQuotationService>>,
    rfq_item_service: Option<Arc<RfqItemService>>,
    rfq_supplier_service: Option<Arc<RfqSupplierService>>,
    supplier_quotation_service: Option<Arc<SupplierQuotationService>>,
    supplier_quotation_item_service: Option<Arc<SupplierQuotationItemService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the MaterialRequest service.
    pub fn with_material_request_service(mut self, service: Arc<MaterialRequestService>) -> Self {
        self.material_request_service = Some(service);
        self
    }

    /// Set the MaterialRequestItem service.
    pub fn with_material_request_item_service(mut self, service: Arc<MaterialRequestItemService>) -> Self {
        self.material_request_item_service = Some(service);
        self
    }

    /// Set the PurchaseOrder service.
    pub fn with_purchase_order_service(mut self, service: Arc<PurchaseOrderService>) -> Self {
        self.purchase_order_service = Some(service);
        self
    }

    /// Set the PurchaseOrderItem service.
    pub fn with_purchase_order_item_service(mut self, service: Arc<PurchaseOrderItemService>) -> Self {
        self.purchase_order_item_service = Some(service);
        self
    }

    /// Set the RequestForQuotation service.
    pub fn with_request_for_quotation_service(mut self, service: Arc<RequestForQuotationService>) -> Self {
        self.request_for_quotation_service = Some(service);
        self
    }

    /// Set the RfqItem service.
    pub fn with_rfq_item_service(mut self, service: Arc<RfqItemService>) -> Self {
        self.rfq_item_service = Some(service);
        self
    }

    /// Set the RfqSupplier service.
    pub fn with_rfq_supplier_service(mut self, service: Arc<RfqSupplierService>) -> Self {
        self.rfq_supplier_service = Some(service);
        self
    }

    /// Set the SupplierQuotation service.
    pub fn with_supplier_quotation_service(mut self, service: Arc<SupplierQuotationService>) -> Self {
        self.supplier_quotation_service = Some(service);
        self
    }

    /// Set the SupplierQuotationItem service.
    pub fn with_supplier_quotation_item_service(mut self, service: Arc<SupplierQuotationItemService>) -> Self {
        self.supplier_quotation_item_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            material_request_service: self.material_request_service.expect("material_request_service is required"),
            material_request_item_service: self.material_request_item_service.expect("material_request_item_service is required"),
            purchase_order_service: self.purchase_order_service.expect("purchase_order_service is required"),
            purchase_order_item_service: self.purchase_order_item_service.expect("purchase_order_item_service is required"),
            request_for_quotation_service: self.request_for_quotation_service.expect("request_for_quotation_service is required"),
            rfq_item_service: self.rfq_item_service.expect("rfq_item_service is required"),
            rfq_supplier_service: self.rfq_supplier_service.expect("rfq_supplier_service is required"),
            supplier_quotation_service: self.supplier_quotation_service.expect("supplier_quotation_service is required"),
            supplier_quotation_item_service: self.supplier_quotation_item_service.expect("supplier_quotation_item_service is required"),
        }
    }
}
