//! Public events for Buying module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// MATERIALREQUEST EVENTS
// ============================================================================

/// Event published when a MaterialRequest is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaterialRequestCreatedEvent {
    pub id: MaterialRequestId,
    pub data: MaterialRequestDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a MaterialRequest is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaterialRequestUpdatedEvent {
    pub id: MaterialRequestId,
    pub data: MaterialRequestDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a MaterialRequest is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaterialRequestDeletedEvent {
    pub id: MaterialRequestId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MATERIALREQUESTITEM EVENTS
// ============================================================================

/// Event published when a MaterialRequestItem is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaterialRequestItemCreatedEvent {
    pub id: MaterialRequestItemId,
    pub data: MaterialRequestItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a MaterialRequestItem is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaterialRequestItemUpdatedEvent {
    pub id: MaterialRequestItemId,
    pub data: MaterialRequestItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a MaterialRequestItem is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaterialRequestItemDeletedEvent {
    pub id: MaterialRequestItemId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PURCHASEAGREEMENT EVENTS
// ============================================================================

/// Event published when a PurchaseAgreement is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseAgreementCreatedEvent {
    pub id: PurchaseAgreementId,
    pub data: PurchaseAgreementDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PurchaseAgreement is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseAgreementUpdatedEvent {
    pub id: PurchaseAgreementId,
    pub data: PurchaseAgreementDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PurchaseAgreement is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseAgreementDeletedEvent {
    pub id: PurchaseAgreementId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PURCHASEAGREEMENTLINE EVENTS
// ============================================================================

/// Event published when a PurchaseAgreementLine is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseAgreementLineCreatedEvent {
    pub id: PurchaseAgreementLineId,
    pub data: PurchaseAgreementLineDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PurchaseAgreementLine is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseAgreementLineUpdatedEvent {
    pub id: PurchaseAgreementLineId,
    pub data: PurchaseAgreementLineDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PurchaseAgreementLine is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseAgreementLineDeletedEvent {
    pub id: PurchaseAgreementLineId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PURCHASECOMPANYSETTING EVENTS
// ============================================================================

/// Event published when a PurchaseCompanySetting is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseCompanySettingCreatedEvent {
    pub id: PurchaseCompanySettingId,
    pub data: PurchaseCompanySettingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PurchaseCompanySetting is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseCompanySettingUpdatedEvent {
    pub id: PurchaseCompanySettingId,
    pub data: PurchaseCompanySettingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PurchaseCompanySetting is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseCompanySettingDeletedEvent {
    pub id: PurchaseCompanySettingId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PURCHASEORDER EVENTS
// ============================================================================

/// Event published when a PurchaseOrder is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseOrderCreatedEvent {
    pub id: PurchaseOrderId,
    pub data: PurchaseOrderDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PurchaseOrder is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseOrderUpdatedEvent {
    pub id: PurchaseOrderId,
    pub data: PurchaseOrderDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PurchaseOrder is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseOrderDeletedEvent {
    pub id: PurchaseOrderId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PURCHASEORDERITEM EVENTS
// ============================================================================

/// Event published when a PurchaseOrderItem is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseOrderItemCreatedEvent {
    pub id: PurchaseOrderItemId,
    pub data: PurchaseOrderItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PurchaseOrderItem is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseOrderItemUpdatedEvent {
    pub id: PurchaseOrderItemId,
    pub data: PurchaseOrderItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PurchaseOrderItem is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseOrderItemDeletedEvent {
    pub id: PurchaseOrderItemId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// REQUESTFORQUOTATION EVENTS
// ============================================================================

/// Event published when a RequestForQuotation is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequestForQuotationCreatedEvent {
    pub id: RequestForQuotationId,
    pub data: RequestForQuotationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a RequestForQuotation is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequestForQuotationUpdatedEvent {
    pub id: RequestForQuotationId,
    pub data: RequestForQuotationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a RequestForQuotation is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequestForQuotationDeletedEvent {
    pub id: RequestForQuotationId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// RFQITEM EVENTS
// ============================================================================

/// Event published when a RfqItem is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RfqItemCreatedEvent {
    pub id: RfqItemId,
    pub data: RfqItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a RfqItem is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RfqItemUpdatedEvent {
    pub id: RfqItemId,
    pub data: RfqItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a RfqItem is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RfqItemDeletedEvent {
    pub id: RfqItemId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// RFQSUPPLIER EVENTS
// ============================================================================

/// Event published when a RfqSupplier is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RfqSupplierCreatedEvent {
    pub id: RfqSupplierId,
    pub data: RfqSupplierDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a RfqSupplier is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RfqSupplierUpdatedEvent {
    pub id: RfqSupplierId,
    pub data: RfqSupplierDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a RfqSupplier is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RfqSupplierDeletedEvent {
    pub id: RfqSupplierId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SUPPLIERPRICE EVENTS
// ============================================================================

/// Event published when a SupplierPrice is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierPriceCreatedEvent {
    pub id: SupplierPriceId,
    pub data: SupplierPriceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SupplierPrice is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierPriceUpdatedEvent {
    pub id: SupplierPriceId,
    pub data: SupplierPriceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SupplierPrice is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierPriceDeletedEvent {
    pub id: SupplierPriceId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SUPPLIERQUOTATION EVENTS
// ============================================================================

/// Event published when a SupplierQuotation is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierQuotationCreatedEvent {
    pub id: SupplierQuotationId,
    pub data: SupplierQuotationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SupplierQuotation is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierQuotationUpdatedEvent {
    pub id: SupplierQuotationId,
    pub data: SupplierQuotationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SupplierQuotation is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierQuotationDeletedEvent {
    pub id: SupplierQuotationId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SUPPLIERQUOTATIONITEM EVENTS
// ============================================================================

/// Event published when a SupplierQuotationItem is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierQuotationItemCreatedEvent {
    pub id: SupplierQuotationItemId,
    pub data: SupplierQuotationItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SupplierQuotationItem is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierQuotationItemUpdatedEvent {
    pub id: SupplierQuotationItemId,
    pub data: SupplierQuotationItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SupplierQuotationItem is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierQuotationItemDeletedEvent {
    pub id: SupplierQuotationItemId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SUPPLIERREMINDERSETTING EVENTS
// ============================================================================

/// Event published when a SupplierReminderSetting is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierReminderSettingCreatedEvent {
    pub id: SupplierReminderSettingId,
    pub data: SupplierReminderSettingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SupplierReminderSetting is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierReminderSettingUpdatedEvent {
    pub id: SupplierReminderSettingId,
    pub data: SupplierReminderSettingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SupplierReminderSetting is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierReminderSettingDeletedEvent {
    pub id: SupplierReminderSettingId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Buying module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum BuyingEvent {
    MaterialRequestCreated(MaterialRequestCreatedEvent),
    MaterialRequestUpdated(MaterialRequestUpdatedEvent),
    MaterialRequestDeleted(MaterialRequestDeletedEvent),
    MaterialRequestItemCreated(MaterialRequestItemCreatedEvent),
    MaterialRequestItemUpdated(MaterialRequestItemUpdatedEvent),
    MaterialRequestItemDeleted(MaterialRequestItemDeletedEvent),
    PurchaseAgreementCreated(PurchaseAgreementCreatedEvent),
    PurchaseAgreementUpdated(PurchaseAgreementUpdatedEvent),
    PurchaseAgreementDeleted(PurchaseAgreementDeletedEvent),
    PurchaseAgreementLineCreated(PurchaseAgreementLineCreatedEvent),
    PurchaseAgreementLineUpdated(PurchaseAgreementLineUpdatedEvent),
    PurchaseAgreementLineDeleted(PurchaseAgreementLineDeletedEvent),
    PurchaseCompanySettingCreated(PurchaseCompanySettingCreatedEvent),
    PurchaseCompanySettingUpdated(PurchaseCompanySettingUpdatedEvent),
    PurchaseCompanySettingDeleted(PurchaseCompanySettingDeletedEvent),
    PurchaseOrderCreated(PurchaseOrderCreatedEvent),
    PurchaseOrderUpdated(PurchaseOrderUpdatedEvent),
    PurchaseOrderDeleted(PurchaseOrderDeletedEvent),
    PurchaseOrderItemCreated(PurchaseOrderItemCreatedEvent),
    PurchaseOrderItemUpdated(PurchaseOrderItemUpdatedEvent),
    PurchaseOrderItemDeleted(PurchaseOrderItemDeletedEvent),
    RequestForQuotationCreated(RequestForQuotationCreatedEvent),
    RequestForQuotationUpdated(RequestForQuotationUpdatedEvent),
    RequestForQuotationDeleted(RequestForQuotationDeletedEvent),
    RfqItemCreated(RfqItemCreatedEvent),
    RfqItemUpdated(RfqItemUpdatedEvent),
    RfqItemDeleted(RfqItemDeletedEvent),
    RfqSupplierCreated(RfqSupplierCreatedEvent),
    RfqSupplierUpdated(RfqSupplierUpdatedEvent),
    RfqSupplierDeleted(RfqSupplierDeletedEvent),
    SupplierPriceCreated(SupplierPriceCreatedEvent),
    SupplierPriceUpdated(SupplierPriceUpdatedEvent),
    SupplierPriceDeleted(SupplierPriceDeletedEvent),
    SupplierQuotationCreated(SupplierQuotationCreatedEvent),
    SupplierQuotationUpdated(SupplierQuotationUpdatedEvent),
    SupplierQuotationDeleted(SupplierQuotationDeletedEvent),
    SupplierQuotationItemCreated(SupplierQuotationItemCreatedEvent),
    SupplierQuotationItemUpdated(SupplierQuotationItemUpdatedEvent),
    SupplierQuotationItemDeleted(SupplierQuotationItemDeletedEvent),
    SupplierReminderSettingCreated(SupplierReminderSettingCreatedEvent),
    SupplierReminderSettingUpdated(SupplierReminderSettingUpdatedEvent),
    SupplierReminderSettingDeleted(SupplierReminderSettingDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuyingEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for BuyingEventMetadata {
    fn default() -> Self {
        Self {
            module: "buying",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
