//! Buying Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Buying exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use buying::exports::{MaterialRequestDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `MaterialRequestDto` - Data transfer object for MaterialRequest
/// - `MaterialRequestSummary` - Summary view of MaterialRequest
/// - `MaterialRequestId` - Type-safe ID wrapper
/// - `MaterialRequestItemDto` - Data transfer object for MaterialRequestItem
/// - `MaterialRequestItemSummary` - Summary view of MaterialRequestItem
/// - `MaterialRequestItemId` - Type-safe ID wrapper
/// - `PurchaseAgreementDto` - Data transfer object for PurchaseAgreement
/// - `PurchaseAgreementSummary` - Summary view of PurchaseAgreement
/// - `PurchaseAgreementId` - Type-safe ID wrapper
/// - `PurchaseAgreementLineDto` - Data transfer object for PurchaseAgreementLine
/// - `PurchaseAgreementLineSummary` - Summary view of PurchaseAgreementLine
/// - `PurchaseAgreementLineId` - Type-safe ID wrapper
/// - `PurchaseCompanySettingDto` - Data transfer object for PurchaseCompanySetting
/// - `PurchaseCompanySettingSummary` - Summary view of PurchaseCompanySetting
/// - `PurchaseCompanySettingId` - Type-safe ID wrapper
/// - `PurchaseOrderDto` - Data transfer object for PurchaseOrder
/// - `PurchaseOrderSummary` - Summary view of PurchaseOrder
/// - `PurchaseOrderId` - Type-safe ID wrapper
/// - `PurchaseOrderItemDto` - Data transfer object for PurchaseOrderItem
/// - `PurchaseOrderItemSummary` - Summary view of PurchaseOrderItem
/// - `PurchaseOrderItemId` - Type-safe ID wrapper
/// - `RequestForQuotationDto` - Data transfer object for RequestForQuotation
/// - `RequestForQuotationSummary` - Summary view of RequestForQuotation
/// - `RequestForQuotationId` - Type-safe ID wrapper
/// - `RfqItemDto` - Data transfer object for RfqItem
/// - `RfqItemSummary` - Summary view of RfqItem
/// - `RfqItemId` - Type-safe ID wrapper
/// - `RfqSupplierDto` - Data transfer object for RfqSupplier
/// - `RfqSupplierSummary` - Summary view of RfqSupplier
/// - `RfqSupplierId` - Type-safe ID wrapper
/// - `SupplierPriceDto` - Data transfer object for SupplierPrice
/// - `SupplierPriceSummary` - Summary view of SupplierPrice
/// - `SupplierPriceId` - Type-safe ID wrapper
/// - `SupplierQuotationDto` - Data transfer object for SupplierQuotation
/// - `SupplierQuotationSummary` - Summary view of SupplierQuotation
/// - `SupplierQuotationId` - Type-safe ID wrapper
/// - `SupplierQuotationItemDto` - Data transfer object for SupplierQuotationItem
/// - `SupplierQuotationItemSummary` - Summary view of SupplierQuotationItem
/// - `SupplierQuotationItemId` - Type-safe ID wrapper
/// - `SupplierReminderSettingDto` - Data transfer object for SupplierReminderSetting
/// - `SupplierReminderSettingSummary` - Summary view of SupplierReminderSetting
/// - `SupplierReminderSettingId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `MaterialRequestCreatedEvent` - Published when MaterialRequest is created
/// - `MaterialRequestUpdatedEvent` - Published when MaterialRequest is updated
/// - `MaterialRequestDeletedEvent` - Published when MaterialRequest is deleted
/// - `MaterialRequestItemCreatedEvent` - Published when MaterialRequestItem is created
/// - `MaterialRequestItemUpdatedEvent` - Published when MaterialRequestItem is updated
/// - `MaterialRequestItemDeletedEvent` - Published when MaterialRequestItem is deleted
/// - `PurchaseAgreementCreatedEvent` - Published when PurchaseAgreement is created
/// - `PurchaseAgreementUpdatedEvent` - Published when PurchaseAgreement is updated
/// - `PurchaseAgreementDeletedEvent` - Published when PurchaseAgreement is deleted
/// - `PurchaseAgreementLineCreatedEvent` - Published when PurchaseAgreementLine is created
/// - `PurchaseAgreementLineUpdatedEvent` - Published when PurchaseAgreementLine is updated
/// - `PurchaseAgreementLineDeletedEvent` - Published when PurchaseAgreementLine is deleted
/// - `PurchaseCompanySettingCreatedEvent` - Published when PurchaseCompanySetting is created
/// - `PurchaseCompanySettingUpdatedEvent` - Published when PurchaseCompanySetting is updated
/// - `PurchaseCompanySettingDeletedEvent` - Published when PurchaseCompanySetting is deleted
/// - `PurchaseOrderCreatedEvent` - Published when PurchaseOrder is created
/// - `PurchaseOrderUpdatedEvent` - Published when PurchaseOrder is updated
/// - `PurchaseOrderDeletedEvent` - Published when PurchaseOrder is deleted
/// - `PurchaseOrderItemCreatedEvent` - Published when PurchaseOrderItem is created
/// - `PurchaseOrderItemUpdatedEvent` - Published when PurchaseOrderItem is updated
/// - `PurchaseOrderItemDeletedEvent` - Published when PurchaseOrderItem is deleted
/// - `RequestForQuotationCreatedEvent` - Published when RequestForQuotation is created
/// - `RequestForQuotationUpdatedEvent` - Published when RequestForQuotation is updated
/// - `RequestForQuotationDeletedEvent` - Published when RequestForQuotation is deleted
/// - `RfqItemCreatedEvent` - Published when RfqItem is created
/// - `RfqItemUpdatedEvent` - Published when RfqItem is updated
/// - `RfqItemDeletedEvent` - Published when RfqItem is deleted
/// - `RfqSupplierCreatedEvent` - Published when RfqSupplier is created
/// - `RfqSupplierUpdatedEvent` - Published when RfqSupplier is updated
/// - `RfqSupplierDeletedEvent` - Published when RfqSupplier is deleted
/// - `SupplierPriceCreatedEvent` - Published when SupplierPrice is created
/// - `SupplierPriceUpdatedEvent` - Published when SupplierPrice is updated
/// - `SupplierPriceDeletedEvent` - Published when SupplierPrice is deleted
/// - `SupplierQuotationCreatedEvent` - Published when SupplierQuotation is created
/// - `SupplierQuotationUpdatedEvent` - Published when SupplierQuotation is updated
/// - `SupplierQuotationDeletedEvent` - Published when SupplierQuotation is deleted
/// - `SupplierQuotationItemCreatedEvent` - Published when SupplierQuotationItem is created
/// - `SupplierQuotationItemUpdatedEvent` - Published when SupplierQuotationItem is updated
/// - `SupplierQuotationItemDeletedEvent` - Published when SupplierQuotationItem is deleted
/// - `SupplierReminderSettingCreatedEvent` - Published when SupplierReminderSetting is created
/// - `SupplierReminderSettingUpdatedEvent` - Published when SupplierReminderSetting is updated
/// - `SupplierReminderSettingDeletedEvent` - Published when SupplierReminderSetting is deleted
pub struct ExportSummary;
