//! Public services for Buying module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Buying module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait BuyingQueryService: Send + Sync {
    /// Get MaterialRequest by ID
    async fn get_material_request(&self, id: MaterialRequestId) -> Result<Option<MaterialRequestDto>>;

    /// Get MaterialRequest summary by ID
    async fn get_material_request_summary(&self, id: MaterialRequestId) -> Result<Option<MaterialRequestSummary>>;

    /// Check if MaterialRequest exists
    async fn material_request_exists(&self, id: MaterialRequestId) -> Result<bool>;

    /// Get MaterialRequestItem by ID
    async fn get_material_request_item(&self, id: MaterialRequestItemId) -> Result<Option<MaterialRequestItemDto>>;

    /// Get MaterialRequestItem summary by ID
    async fn get_material_request_item_summary(&self, id: MaterialRequestItemId) -> Result<Option<MaterialRequestItemSummary>>;

    /// Check if MaterialRequestItem exists
    async fn material_request_item_exists(&self, id: MaterialRequestItemId) -> Result<bool>;

    /// Get PurchaseOrder by ID
    async fn get_purchase_order(&self, id: PurchaseOrderId) -> Result<Option<PurchaseOrderDto>>;

    /// Get PurchaseOrder summary by ID
    async fn get_purchase_order_summary(&self, id: PurchaseOrderId) -> Result<Option<PurchaseOrderSummary>>;

    /// Check if PurchaseOrder exists
    async fn purchase_order_exists(&self, id: PurchaseOrderId) -> Result<bool>;

    /// Get PurchaseOrderItem by ID
    async fn get_purchase_order_item(&self, id: PurchaseOrderItemId) -> Result<Option<PurchaseOrderItemDto>>;

    /// Get PurchaseOrderItem summary by ID
    async fn get_purchase_order_item_summary(&self, id: PurchaseOrderItemId) -> Result<Option<PurchaseOrderItemSummary>>;

    /// Check if PurchaseOrderItem exists
    async fn purchase_order_item_exists(&self, id: PurchaseOrderItemId) -> Result<bool>;

    /// Get RequestForQuotation by ID
    async fn get_request_for_quotation(&self, id: RequestForQuotationId) -> Result<Option<RequestForQuotationDto>>;

    /// Get RequestForQuotation summary by ID
    async fn get_request_for_quotation_summary(&self, id: RequestForQuotationId) -> Result<Option<RequestForQuotationSummary>>;

    /// Check if RequestForQuotation exists
    async fn request_for_quotation_exists(&self, id: RequestForQuotationId) -> Result<bool>;

    /// Get RfqItem by ID
    async fn get_rfq_item(&self, id: RfqItemId) -> Result<Option<RfqItemDto>>;

    /// Get RfqItem summary by ID
    async fn get_rfq_item_summary(&self, id: RfqItemId) -> Result<Option<RfqItemSummary>>;

    /// Check if RfqItem exists
    async fn rfq_item_exists(&self, id: RfqItemId) -> Result<bool>;

    /// Get RfqSupplier by ID
    async fn get_rfq_supplier(&self, id: RfqSupplierId) -> Result<Option<RfqSupplierDto>>;

    /// Get RfqSupplier summary by ID
    async fn get_rfq_supplier_summary(&self, id: RfqSupplierId) -> Result<Option<RfqSupplierSummary>>;

    /// Check if RfqSupplier exists
    async fn rfq_supplier_exists(&self, id: RfqSupplierId) -> Result<bool>;

    /// Get SupplierQuotation by ID
    async fn get_supplier_quotation(&self, id: SupplierQuotationId) -> Result<Option<SupplierQuotationDto>>;

    /// Get SupplierQuotation summary by ID
    async fn get_supplier_quotation_summary(&self, id: SupplierQuotationId) -> Result<Option<SupplierQuotationSummary>>;

    /// Check if SupplierQuotation exists
    async fn supplier_quotation_exists(&self, id: SupplierQuotationId) -> Result<bool>;

    /// Get SupplierQuotationItem by ID
    async fn get_supplier_quotation_item(&self, id: SupplierQuotationItemId) -> Result<Option<SupplierQuotationItemDto>>;

    /// Get SupplierQuotationItem summary by ID
    async fn get_supplier_quotation_item_summary(&self, id: SupplierQuotationItemId) -> Result<Option<SupplierQuotationItemSummary>>;

    /// Check if SupplierQuotationItem exists
    async fn supplier_quotation_item_exists(&self, id: SupplierQuotationItemId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of BuyingQueryService
pub struct BuyingQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> BuyingQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
