//! Public types for Buying module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// MATERIALREQUEST TYPES
// ============================================================================

/// Type-safe ID for MaterialRequest
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MaterialRequestId(pub Uuid);

impl MaterialRequestId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for MaterialRequestId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<MaterialRequestId> for Uuid {
    fn from(id: MaterialRequestId) -> Self {
        id.0
    }
}

/// Data transfer object for MaterialRequest
///
/// This is the public representation of MaterialRequest for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaterialRequestDto {
    pub id: MaterialRequestId,
    pub request_number: String,
    pub company_id: Uuid,
    pub request_type: MaterialRequestType,
    pub status: PurchaseDocStatus,
    pub request_date: NaiveDate,
    pub schedule_date: Option<NaiveDate>,
    pub notes: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of MaterialRequest for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaterialRequestSummary {
    pub id: MaterialRequestId,
    pub status: PurchaseDocStatus,
}

/// Reference to MaterialRequest for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaterialRequestRef {
    pub id: MaterialRequestId,
}

// ============================================================================
// MATERIALREQUESTITEM TYPES
// ============================================================================

/// Type-safe ID for MaterialRequestItem
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MaterialRequestItemId(pub Uuid);

impl MaterialRequestItemId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for MaterialRequestItemId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<MaterialRequestItemId> for Uuid {
    fn from(id: MaterialRequestItemId) -> Self {
        id.0
    }
}

/// Data transfer object for MaterialRequestItem
///
/// This is the public representation of MaterialRequestItem for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaterialRequestItemDto {
    pub id: MaterialRequestItemId,
    pub request_id: Uuid,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub metadata: serde_json::Value,
}

/// Summary view of MaterialRequestItem for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaterialRequestItemSummary {
    pub id: MaterialRequestItemId,
}

/// Reference to MaterialRequestItem for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaterialRequestItemRef {
    pub id: MaterialRequestItemId,
}

// ============================================================================
// PURCHASEORDER TYPES
// ============================================================================

/// Type-safe ID for PurchaseOrder
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PurchaseOrderId(pub Uuid);

impl PurchaseOrderId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PurchaseOrderId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PurchaseOrderId> for Uuid {
    fn from(id: PurchaseOrderId) -> Self {
        id.0
    }
}

/// Data transfer object for PurchaseOrder
///
/// This is the public representation of PurchaseOrder for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseOrderDto {
    pub id: PurchaseOrderId,
    pub po_number: String,
    pub supplier_quotation_id: Option<Uuid>,
    pub order_kind: OrderKind,
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub supplier_id: Uuid,
    pub status: PurchaseOrderStatus,
    pub order_date: NaiveDate,
    pub schedule_date: Option<NaiveDate>,
    pub currency: String,
    pub subtotal: Decimal,
    pub tax_rate: Decimal,
    pub tax_amount: Decimal,
    pub total: Decimal,
    pub notes: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of PurchaseOrder for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseOrderSummary {
    pub id: PurchaseOrderId,
    pub status: PurchaseOrderStatus,
}

/// Reference to PurchaseOrder for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseOrderRef {
    pub id: PurchaseOrderId,
}

// ============================================================================
// PURCHASEORDERITEM TYPES
// ============================================================================

/// Type-safe ID for PurchaseOrderItem
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PurchaseOrderItemId(pub Uuid);

impl PurchaseOrderItemId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PurchaseOrderItemId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PurchaseOrderItemId> for Uuid {
    fn from(id: PurchaseOrderItemId) -> Self {
        id.0
    }
}

/// Data transfer object for PurchaseOrderItem
///
/// This is the public representation of PurchaseOrderItem for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseOrderItemDto {
    pub id: PurchaseOrderItemId,
    pub order_id: Uuid,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub warehouse_id: Option<Uuid>,
    pub description: Option<String>,
    pub quantity: Decimal,
    pub rate: Decimal,
    pub line_amount: Decimal,
    pub received_qty: Decimal,
    pub billed_qty: Decimal,
    pub metadata: serde_json::Value,
}

/// Summary view of PurchaseOrderItem for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseOrderItemSummary {
    pub id: PurchaseOrderItemId,
}

/// Reference to PurchaseOrderItem for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseOrderItemRef {
    pub id: PurchaseOrderItemId,
}

// ============================================================================
// REQUESTFORQUOTATION TYPES
// ============================================================================

/// Type-safe ID for RequestForQuotation
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RequestForQuotationId(pub Uuid);

impl RequestForQuotationId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for RequestForQuotationId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<RequestForQuotationId> for Uuid {
    fn from(id: RequestForQuotationId) -> Self {
        id.0
    }
}

/// Data transfer object for RequestForQuotation
///
/// This is the public representation of RequestForQuotation for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequestForQuotationDto {
    pub id: RequestForQuotationId,
    pub rfq_number: String,
    pub material_request_id: Option<Uuid>,
    pub company_id: Uuid,
    pub status: PurchaseDocStatus,
    pub rfq_date: NaiveDate,
    pub response_due: Option<NaiveDate>,
    pub metadata: serde_json::Value,
}

/// Summary view of RequestForQuotation for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequestForQuotationSummary {
    pub id: RequestForQuotationId,
    pub status: PurchaseDocStatus,
}

/// Reference to RequestForQuotation for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequestForQuotationRef {
    pub id: RequestForQuotationId,
}

// ============================================================================
// RFQITEM TYPES
// ============================================================================

/// Type-safe ID for RfqItem
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RfqItemId(pub Uuid);

impl RfqItemId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for RfqItemId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<RfqItemId> for Uuid {
    fn from(id: RfqItemId) -> Self {
        id.0
    }
}

/// Data transfer object for RfqItem
///
/// This is the public representation of RfqItem for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RfqItemDto {
    pub id: RfqItemId,
    pub rfq_id: Uuid,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub metadata: serde_json::Value,
}

/// Summary view of RfqItem for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RfqItemSummary {
    pub id: RfqItemId,
}

/// Reference to RfqItem for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RfqItemRef {
    pub id: RfqItemId,
}

// ============================================================================
// RFQSUPPLIER TYPES
// ============================================================================

/// Type-safe ID for RfqSupplier
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RfqSupplierId(pub Uuid);

impl RfqSupplierId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for RfqSupplierId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<RfqSupplierId> for Uuid {
    fn from(id: RfqSupplierId) -> Self {
        id.0
    }
}

/// Data transfer object for RfqSupplier
///
/// This is the public representation of RfqSupplier for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RfqSupplierDto {
    pub id: RfqSupplierId,
    pub rfq_id: Uuid,
    pub company_id: Uuid,
    pub supplier_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of RfqSupplier for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RfqSupplierSummary {
    pub id: RfqSupplierId,
}

/// Reference to RfqSupplier for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RfqSupplierRef {
    pub id: RfqSupplierId,
}

// ============================================================================
// SUPPLIERQUOTATION TYPES
// ============================================================================

/// Type-safe ID for SupplierQuotation
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SupplierQuotationId(pub Uuid);

impl SupplierQuotationId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SupplierQuotationId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SupplierQuotationId> for Uuid {
    fn from(id: SupplierQuotationId) -> Self {
        id.0
    }
}

/// Data transfer object for SupplierQuotation
///
/// This is the public representation of SupplierQuotation for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierQuotationDto {
    pub id: SupplierQuotationId,
    pub quotation_number: String,
    pub rfq_id: Option<Uuid>,
    pub company_id: Uuid,
    pub supplier_id: Uuid,
    pub status: PurchaseDocStatus,
    pub quotation_date: NaiveDate,
    pub valid_till: Option<NaiveDate>,
    pub currency: String,
    pub notes: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of SupplierQuotation for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierQuotationSummary {
    pub id: SupplierQuotationId,
    pub status: PurchaseDocStatus,
}

/// Reference to SupplierQuotation for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierQuotationRef {
    pub id: SupplierQuotationId,
}

// ============================================================================
// SUPPLIERQUOTATIONITEM TYPES
// ============================================================================

/// Type-safe ID for SupplierQuotationItem
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SupplierQuotationItemId(pub Uuid);

impl SupplierQuotationItemId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SupplierQuotationItemId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SupplierQuotationItemId> for Uuid {
    fn from(id: SupplierQuotationItemId) -> Self {
        id.0
    }
}

/// Data transfer object for SupplierQuotationItem
///
/// This is the public representation of SupplierQuotationItem for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierQuotationItemDto {
    pub id: SupplierQuotationItemId,
    pub quotation_id: Uuid,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub rate: Decimal,
    pub lead_time_days: Option<i32>,
    pub metadata: serde_json::Value,
}

/// Summary view of SupplierQuotationItem for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierQuotationItemSummary {
    pub id: SupplierQuotationItemId,
}

/// Reference to SupplierQuotationItem for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SupplierQuotationItemRef {
    pub id: SupplierQuotationItemId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
