//! Use case type aliases for MaterialRequest aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateMaterialRequestDto, UpdateMaterialRequestDto};
use crate::application::service::MaterialRequestService;
use crate::domain::entity::MaterialRequest;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateMaterialRequestUseCase = CreateUseCase<MaterialRequest, CreateMaterialRequestDto, MaterialRequestService>;
pub type UpdateMaterialRequestUseCase = UpdateUseCase<MaterialRequest, UpdateMaterialRequestDto, MaterialRequestService>;
pub type GetMaterialRequestUseCase    = GetUseCase<MaterialRequest, MaterialRequestService>;
pub type DeleteMaterialRequestUseCase = DeleteUseCase<MaterialRequest, MaterialRequestService>;
pub type ListMaterialRequestUseCase   = ListUseCase<MaterialRequest, MaterialRequestService>;

// <<< CUSTOM
// END CUSTOM
