//! Use case type aliases for RequestForQuotation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateRequestForQuotationDto, UpdateRequestForQuotationDto};
use crate::application::service::RequestForQuotationService;
use crate::domain::entity::RequestForQuotation;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateRequestForQuotationUseCase = CreateUseCase<RequestForQuotation, CreateRequestForQuotationDto, RequestForQuotationService>;
pub type UpdateRequestForQuotationUseCase = UpdateUseCase<RequestForQuotation, UpdateRequestForQuotationDto, RequestForQuotationService>;
pub type GetRequestForQuotationUseCase    = GetUseCase<RequestForQuotation, RequestForQuotationService>;
pub type DeleteRequestForQuotationUseCase = DeleteUseCase<RequestForQuotation, RequestForQuotationService>;
pub type ListRequestForQuotationUseCase   = ListUseCase<RequestForQuotation, RequestForQuotationService>;

// <<< CUSTOM
// END CUSTOM
