//! Use case type aliases for RfqSupplier aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateRfqSupplierDto, UpdateRfqSupplierDto};
use crate::application::service::RfqSupplierService;
use crate::domain::entity::RfqSupplier;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateRfqSupplierUseCase = CreateUseCase<RfqSupplier, CreateRfqSupplierDto, RfqSupplierService>;
pub type UpdateRfqSupplierUseCase = UpdateUseCase<RfqSupplier, UpdateRfqSupplierDto, RfqSupplierService>;
pub type GetRfqSupplierUseCase    = GetUseCase<RfqSupplier, RfqSupplierService>;
pub type DeleteRfqSupplierUseCase = DeleteUseCase<RfqSupplier, RfqSupplierService>;
pub type ListRfqSupplierUseCase   = ListUseCase<RfqSupplier, RfqSupplierService>;

// <<< CUSTOM
// END CUSTOM
