//! Use case type aliases for SupplierQuotation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateSupplierQuotationDto, UpdateSupplierQuotationDto};
use crate::application::service::SupplierQuotationService;
use crate::domain::entity::SupplierQuotation;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateSupplierQuotationUseCase = CreateUseCase<SupplierQuotation, CreateSupplierQuotationDto, SupplierQuotationService>;
pub type UpdateSupplierQuotationUseCase = UpdateUseCase<SupplierQuotation, UpdateSupplierQuotationDto, SupplierQuotationService>;
pub type GetSupplierQuotationUseCase    = GetUseCase<SupplierQuotation, SupplierQuotationService>;
pub type DeleteSupplierQuotationUseCase = DeleteUseCase<SupplierQuotation, SupplierQuotationService>;
pub type ListSupplierQuotationUseCase   = ListUseCase<SupplierQuotation, SupplierQuotationService>;

// <<< CUSTOM
// END CUSTOM
