//! HTTP handlers
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod material_request_handler;
pub mod material_request_item_handler;
pub mod purchase_order_handler;
pub mod purchase_order_item_handler;
pub mod request_for_quotation_handler;
pub mod rfq_item_handler;
pub mod rfq_supplier_handler;
pub mod supplier_quotation_handler;
pub mod supplier_quotation_item_handler;

// <<< CUSTOM
pub mod guarded_routes;
// END CUSTOM

// Re-exports
pub use material_request_handler::{create_material_request_routes, create_material_request_read_routes, create_material_request_write_routes};
pub use material_request_item_handler::{create_material_request_item_routes, create_material_request_item_read_routes, create_material_request_item_write_routes};
pub use purchase_order_handler::{create_purchase_order_routes, create_purchase_order_read_routes, create_purchase_order_write_routes};
pub use purchase_order_item_handler::{create_purchase_order_item_routes, create_purchase_order_item_read_routes, create_purchase_order_item_write_routes};
pub use request_for_quotation_handler::{create_request_for_quotation_routes, create_request_for_quotation_read_routes, create_request_for_quotation_write_routes};
pub use rfq_item_handler::{create_rfq_item_routes, create_rfq_item_read_routes, create_rfq_item_write_routes};
pub use rfq_supplier_handler::{create_rfq_supplier_routes, create_rfq_supplier_read_routes, create_rfq_supplier_write_routes};
pub use supplier_quotation_handler::{create_supplier_quotation_routes, create_supplier_quotation_read_routes, create_supplier_quotation_write_routes};
pub use supplier_quotation_item_handler::{create_supplier_quotation_item_routes, create_supplier_quotation_item_read_routes, create_supplier_quotation_item_write_routes};
// <<< CUSTOM
pub use guarded_routes::create_guarded_buying_routes;
// END CUSTOM